# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

MODULE_AUTHOR="RCAPUTO"

inherit perl-module

DESCRIPTION="Reusable tests for POE::Loop authors"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"

DEPEND="dev-perl/POE"

SRC_TEST="do"
