# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

DESCRIPTION="Tie a variable to shared memory"
HOMEPAGE="http://search.cpan.org/search?query=IPC-Shareable&mode=dist"
SRC_URI="mirror://cpan/authors/id/B/BS/BSUGARS/IPC-Shareable-0.60.tar.gz"

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="dev-lang/perl"
RDEPEND="${DEPEND}"
