#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/dev-db/pgpool/files/pgpool.init,v 1.1 2003/10/13 00:21:25 nakano Exp $

depend() {
	need net
	use postgresql
}

start() {
	ebegin "Starting pgpool"
	start-stop-daemon --start --quiet --exec /usr/bin/pgpool
	result=$?
	eend $result
}

stop() {
	ebegin "Stopping pgpool"
	start-stop-daemon --stop --quiet --pidfile /var/run/pgpool.pid
	result=$?
	eend $result
}
