#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-db/pgpool/files/pgpool.init,v 1.3 2004/07/14 21:41:38 agriffis Exp $

depend() {
	need net
	use postgresql
}

start() {
	ebegin "Starting pgpool"
	start-stop-daemon --start --quiet --exec /usr/bin/pgpool
	result=$?
	eend $result
}

stop() {
	ebegin "Stopping pgpool"
	start-stop-daemon --stop --quiet --pidfile /var/run/pgpool.pid
	result=$?
	eend $result
}
