#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later

depend() {
	need net
}

start() {
	ebegin "Starting cvsd"
	start-stop-daemon --start --quiet --background --exec /usr/sbin/cvsd -- ${CVSD_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping cvsd"
	start-stop-daemon --stop --quiet --exec /usr/sbin/cvsd
	eend $?
}
