# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/eclipse-sdk/eclipse-sdk-2.1.ebuild,v 1.7 2004/01/07 20:28:39 mr_bones_ Exp $

DESCRIPTION="Eclipse Tools Platform"
HOMEPAGE="http://www.eclipse.org/"
SRC_URI="http://download.eclipse.org/downloads/drops/R-2.1-200303272130/eclipse-sourceBuild-srcIncluded-2.1.zip"
LICENSE="CPL-1.0"
SLOT="0"
KEYWORDS="~x86 -ppc -sparc"
RDEPEND=">=virtual/jdk-1.3
	>=x11-libs/gtk+-2.2.1-r1
	=gnome-base/gnome-vfs-2*"

DEPEND="${RDEPEND}
	>=virtual/jdk-1.3
	>=dev-java/ant-1.4
	ppc? ( app-shells/tcsh )"

src_unpack() {
	mkdir ${S}
	cd ${S}
	unpack ${A}
}

src_compile() {
	build -os linux -ws gtk
}

src_install() {
	dodir /opt/eclipse
	copy_files "" "${base_files}"
	copy_files "1.5.2" "${ant_files}"
	copy_files "4.0.7" "${xerces_files}"
	copy_files "4.0.6" "${tomcat_files}"
	copy_files "1.2.1" "${lucene_files}"
	copy_files "2.1.0" "${eclipse_files}"

	dodoc plugins/org.eclipse.platform/{notice,about,cpl-v10}.html

	insinto /usr/share/gnome/apps/Development
	doins ${FILESDIR}/eclipse.desktop
}

copy_files() {
	version=$1
	files=$2
	for d in ${files} ; do
		s=${d/_$version/}
		if [ -d ${s} ] ; then
			dodir /opt/eclipse/${d}
		elif [ -f ${s} ] ; then
			cp ${s} ${D}/opt/eclipse/${d}
		elif [ -d ${s}-feature ] ; then
			dodir /opt/eclipse/${d}
		elif [ -f ${d/_${version}/-feature} ] ; then
			cp ${d/_${version}/-feature} ${D}/opt/eclipse/${d}
		else
			echo "Invalid file: ${d}!"
		fi
	done
}

xerces_files="
plugins/org.apache.xerces_4.0.7
plugins/org.apache.xerces_4.0.7/plugin.xml
plugins/org.apache.xerces_4.0.7/xmlParserAPIs.jar
plugins/org.apache.xerces_4.0.7/about.html
plugins/org.apache.xerces_4.0.7/xercesImpl.jar
plugins/org.apache.xerces_4.0.7/plugin.properties
"

ant_files="
plugins/org.apache.ant_1.5.2
plugins/org.apache.ant_1.5.2/plugin.xml
plugins/org.apache.ant_1.5.2/about.html
plugins/org.apache.ant_1.5.2/ant.jar
plugins/org.apache.ant_1.5.2/plugin.properties
plugins/org.apache.ant_1.5.2/optional.jar
"
tomcat_files="
plugins/org.eclipse.tomcat_4.0.6
plugins/org.eclipse.tomcat_4.0.6/webapps
plugins/org.eclipse.tomcat_4.0.6/webapps/ROOT
plugins/org.eclipse.tomcat_4.0.6/webapps/ROOT/WEB-INF
plugins/org.eclipse.tomcat_4.0.6/webapps/ROOT/WEB-INF/web.xml
plugins/org.eclipse.tomcat_4.0.6/webapps/ROOT/index.html
plugins/org.eclipse.tomcat_4.0.6/conf
plugins/org.eclipse.tomcat_4.0.6/conf/catalina.policy
plugins/org.eclipse.tomcat_4.0.6/conf/web.xml
plugins/org.eclipse.tomcat_4.0.6/conf/tomcat-users.xml
plugins/org.eclipse.tomcat_4.0.6/tomcatwrapper.jar
plugins/org.eclipse.tomcat_4.0.6/servlets-default.jar
plugins/org.eclipse.tomcat_4.0.6/jakarta-regexp-1.2.jar
plugins/org.eclipse.tomcat_4.0.6/plugin.properties
plugins/org.eclipse.tomcat_4.0.6/commons-logging.jar
plugins/org.eclipse.tomcat_4.0.6/naming-resources.jar
plugins/org.eclipse.tomcat_4.0.6/servlet.jar
plugins/org.eclipse.tomcat_4.0.6/servlets-common.jar
plugins/org.eclipse.tomcat_4.0.6/naming-common.jar
plugins/org.eclipse.tomcat_4.0.6/servlets-manager.jar
plugins/org.eclipse.tomcat_4.0.6/servlets-webdav.jar
plugins/org.eclipse.tomcat_4.0.6/catalina.jar
plugins/org.eclipse.tomcat_4.0.6/jasper-compiler.jar
plugins/org.eclipse.tomcat_4.0.6/tomcat-util.jar
plugins/org.eclipse.tomcat_4.0.6/tomcat-http11.jar
plugins/org.eclipse.tomcat_4.0.6/naming-factory.jar
plugins/org.eclipse.tomcat_4.0.6/servlets-invoker.jar
plugins/org.eclipse.tomcat_4.0.6/about.html
plugins/org.eclipse.tomcat_4.0.6/bootstrap.jar
plugins/org.eclipse.tomcat_4.0.6/plugin.xml
plugins/org.eclipse.tomcat_4.0.6/jasper-runtime.jar
plugins/org.eclipse.tomcat_4.0.6/tomcat-coyote.jar
"
lucene_files="
plugins/org.apache.lucene_1.2.1
plugins/org.apache.lucene_1.2.1/parser.jar
plugins/org.apache.lucene_1.2.1/plugin.properties
plugins/org.apache.lucene_1.2.1/about.html
plugins/org.apache.lucene_1.2.1/plugin.xml
plugins/org.apache.lucene_1.2.1/lucene-1.2.jar
"

eclipse_files="
plugins/org.eclipse.core.boot_2.1.0
plugins/org.eclipse.core.boot_2.1.0/boot.jar
plugins/org.eclipse.core.boot_2.1.0/splash.bmp
plugins/org.eclipse.core.boot_2.1.0/boot.xml
plugins/org.eclipse.core.boot_2.1.0/plugin.properties
plugins/org.eclipse.core.boot_2.1.0/plugin.xml
plugins/org.eclipse.core.boot_2.1.0/.options
plugins/org.eclipse.core.boot_2.1.0/about.html
plugins/org.eclipse.core.runtime_2.1.0
plugins/org.eclipse.core.runtime_2.1.0/runtime.jar
plugins/org.eclipse.core.runtime_2.1.0/plugin.properties
plugins/org.eclipse.core.runtime_2.1.0/.options
plugins/org.eclipse.core.runtime_2.1.0/plugin.xml
plugins/org.eclipse.core.runtime_2.1.0/about.html
plugins/org.eclipse.update.core_2.1.0
plugins/org.eclipse.update.core_2.1.0/updatecore.jar
plugins/org.eclipse.update.core_2.1.0/plugin.properties
plugins/org.eclipse.update.core_2.1.0/.options
plugins/org.eclipse.update.core_2.1.0/plugin.xml
plugins/org.eclipse.update.core_2.1.0/about.html
plugins/org.eclipse.swt_2.1.0
plugins/org.eclipse.swt_2.1.0/plugin.properties
plugins/org.eclipse.swt_2.1.0/plugin.xml
plugins/org.eclipse.swt_2.1.0/about.html
plugins/org.eclipse.platform.doc.user_2.1.0
plugins/org.eclipse.platform.doc.user_2.1.0/doc.zip
plugins/org.eclipse.platform.doc.user_2.1.0/about.html
plugins/org.eclipse.platform.doc.user_2.1.0/workbench.gif
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_Search.xml
plugins/org.eclipse.platform.doc.user_2.1.0/hglegal.htm
plugins/org.eclipse.platform.doc.user_2.1.0/hglegal2002.htm
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_ExternalTools.xml
plugins/org.eclipse.platform.doc.user_2.1.0/no_help_exists.htm
plugins/org.eclipse.platform.doc.user_2.1.0/ngibmcpy2002.gif
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_Workbench.xml
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_Team_CVS.xml
plugins/org.eclipse.platform.doc.user_2.1.0/topics_Concepts.xml
plugins/org.eclipse.platform.doc.user_2.1.0/plugin.properties
plugins/org.eclipse.platform.doc.user_2.1.0/plugin.xml
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_Compare.xml
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_Update.xml
plugins/org.eclipse.platform.doc.user_2.1.0/contexts_Team.xml
plugins/org.eclipse.platform.doc.user_2.1.0/topics_GettingStarted.xml
plugins/org.eclipse.platform.doc.user_2.1.0/book.css
plugins/org.eclipse.platform.doc.user_2.1.0/topics_Tasks.xml
plugins/org.eclipse.platform.doc.user_2.1.0/toc.xml
plugins/org.eclipse.platform.doc.user_2.1.0/hglegal2003.htm
plugins/org.eclipse.platform.doc.user_2.1.0/topics_Reference.xml
plugins/org.eclipse.platform.doc.user_2.1.0/ngibmcpy2003.gif
plugins/org.eclipse.platform.doc.user_2.1.0/ngibmcpy.gif
plugins/org.eclipse.ant.core_2.1.0
plugins/org.eclipse.ant.core_2.1.0/lib
plugins/org.eclipse.ant.core_2.1.0/lib/antsupportlib.jar
plugins/org.eclipse.ant.core_2.1.0/antsupport.jar
plugins/org.eclipse.ant.core_2.1.0/plugin.properties
plugins/org.eclipse.ant.core_2.1.0/plugin.xml
plugins/org.eclipse.ant.core_2.1.0/.options
plugins/org.eclipse.ant.core_2.1.0/about.html
plugins/org.eclipse.core.resources_2.1.0
plugins/org.eclipse.core.resources_2.1.0/ant_tasks
plugins/org.eclipse.core.resources_2.1.0/ant_tasks/resources-ant.jar
plugins/org.eclipse.core.resources_2.1.0/ant_tasks/readme.txt
plugins/org.eclipse.core.resources_2.1.0/resources.jar
plugins/org.eclipse.core.resources_2.1.0/.options
plugins/org.eclipse.core.resources_2.1.0/plugin.properties
plugins/org.eclipse.core.resources_2.1.0/plugin.xml
plugins/org.eclipse.core.resources_2.1.0/about.html
plugins/org.eclipse.help.appserver_2.1.0
plugins/org.eclipse.help.appserver_2.1.0/doc
plugins/org.eclipse.help.appserver_2.1.0/doc/hglegal2003.htm
plugins/org.eclipse.help.appserver_2.1.0/doc/org_eclipse_help_appserver.html
plugins/org.eclipse.help.appserver_2.1.0/doc/ngibmcpy2003.gif
plugins/org.eclipse.help.appserver_2.1.0/appserver.jar
plugins/org.eclipse.help.appserver_2.1.0/preferences.ini
plugins/org.eclipse.help.appserver_2.1.0/plugin.properties
plugins/org.eclipse.help.appserver_2.1.0/plugin.xml
plugins/org.eclipse.help.appserver_2.1.0/about.html
plugins/org.eclipse.text_2.1.0
plugins/org.eclipse.text_2.1.0/text.jar
plugins/org.eclipse.text_2.1.0/plugin.properties
plugins/org.eclipse.text_2.1.0/plugin.xml
plugins/org.eclipse.text_2.1.0/about.html
plugins/org.eclipse.platform_2.1.0
plugins/org.eclipse.platform_2.1.0/eclipse_lg.gif
plugins/org.eclipse.platform_2.1.0/about.properties
plugins/org.eclipse.platform_2.1.0/welcome.xml
plugins/org.eclipse.platform_2.1.0/eclipse.gif
plugins/org.eclipse.platform_2.1.0/plugin.properties
plugins/org.eclipse.platform_2.1.0/plugin_customization.properties
plugins/org.eclipse.platform_2.1.0/plugin.xml
plugins/org.eclipse.platform_2.1.0/splash.bmp
plugins/org.eclipse.platform_2.1.0/plugin_customization.ini
plugins/org.eclipse.platform_2.1.0/about.html
plugins/org.eclipse.platform_2.1.0/about.mappings
plugins/org.eclipse.platform_2.1.0/eclipse32.gif
plugins/org.eclipse.platform_2.1.0/about.ini
plugins/org.eclipse.team.core_2.1.0
plugins/org.eclipse.team.core_2.1.0/team.jar
plugins/org.eclipse.team.core_2.1.0/.options
plugins/org.eclipse.team.core_2.1.0/plugin.properties
plugins/org.eclipse.team.core_2.1.0/plugin.xml
plugins/org.eclipse.team.core_2.1.0/about.html
plugins/org.eclipse.jface_2.1.0
plugins/org.eclipse.jface_2.1.0/jface.jar
plugins/org.eclipse.jface_2.1.0/about.html
plugins/org.eclipse.jface_2.1.0/plugin.xml
plugins/org.eclipse.jface_2.1.0/plugin.properties
plugins/org.eclipse.help_2.1.0
plugins/org.eclipse.help_2.1.0/doc
plugins/org.eclipse.help_2.1.0/doc/helpsample.jpg
plugins/org.eclipse.help_2.1.0/doc/help_home.html
plugins/org.eclipse.help_2.1.0/doc/hglegal2003.htm
plugins/org.eclipse.help_2.1.0/doc/ngibmcpy2003.gif
plugins/org.eclipse.help_2.1.0/doc/book.css
plugins/org.eclipse.help_2.1.0/doc/org_eclipse_help.html
plugins/org.eclipse.help_2.1.0/doc/search_results_view.gif
plugins/org.eclipse.help_2.1.0/doc/banner_prod.jpg
plugins/org.eclipse.help_2.1.0/doc/synch_toc_nav.gif
plugins/org.eclipse.help_2.1.0/doc/contents_view.gif
plugins/org.eclipse.help_2.1.0/dtd
plugins/org.eclipse.help_2.1.0/dtd/toc.dtd
plugins/org.eclipse.help_2.1.0/dtd/contexts.dtd
plugins/org.eclipse.help_2.1.0/help.jar
plugins/org.eclipse.help_2.1.0/.options
plugins/org.eclipse.help_2.1.0/plugin.properties
plugins/org.eclipse.help_2.1.0/preferences.ini
plugins/org.eclipse.help_2.1.0/about.html
plugins/org.eclipse.help_2.1.0/livehelp.js
plugins/org.eclipse.help_2.1.0/plugin.xml
plugins/org.eclipse.debug.core_2.1.0
plugins/org.eclipse.debug.core_2.1.0/dtcore.jar
plugins/org.eclipse.debug.core_2.1.0/about.html
plugins/org.eclipse.debug.core_2.1.0/plugin.xml
plugins/org.eclipse.debug.core_2.1.0/.options
plugins/org.eclipse.debug.core_2.1.0/plugin.properties
plugins/org.eclipse.jface.text_2.1.0
plugins/org.eclipse.jface.text_2.1.0/jfacetext.jar
plugins/org.eclipse.jface.text_2.1.0/plugin.xml
plugins/org.eclipse.jface.text_2.1.0/about.html
plugins/org.eclipse.jface.text_2.1.0/plugin.properties
plugins/org.eclipse.team.cvs.core_2.1.0
plugins/org.eclipse.team.cvs.core_2.1.0/cvs.jar
plugins/org.eclipse.team.cvs.core_2.1.0/plugin.properties
plugins/org.eclipse.team.cvs.core_2.1.0/.options
plugins/org.eclipse.team.cvs.core_2.1.0/plugin.xml
plugins/org.eclipse.team.cvs.core_2.1.0/about.html
plugins/org.eclipse.help.webapp_2.1.0
plugins/org.eclipse.help.webapp_2.1.0/WEB-INF
plugins/org.eclipse.help.webapp_2.1.0/WEB-INF/lib
plugins/org.eclipse.help.webapp_2.1.0/WEB-INF/lib/servlets.jar
plugins/org.eclipse.help.webapp_2.1.0/WEB-INF/lib/jsp.jar
plugins/org.eclipse.help.webapp_2.1.0/WEB-INF/web.xml
plugins/org.eclipse.help.webapp_2.1.0/basic
plugins/org.eclipse.help.webapp_2.1.0/basic/images
plugins/org.eclipse.help.webapp_2.1.0/basic/images/topic.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/search_results_view.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/toc_closed.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/links_view.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/contents_view.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/toc_open.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/synch_toc_nav.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/bookmarks_view.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/bookmark_obj.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/images/container_obj.gif
plugins/org.eclipse.help.webapp_2.1.0/basic/toolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/searchView.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/tocToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/help.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/advanced.inc
plugins/org.eclipse.help.webapp_2.1.0/basic/bookmarksView.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/tabs.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/index.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/tocView.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/header.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/view.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/livehelp.js.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/bookmarksToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/searchToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/err.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/linksToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/basic/linksView.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced
plugins/org.eclipse.help.webapp_2.1.0/advanced/images
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/return.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/contents_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/bannerBar.jpg
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/prod.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/hide_nav.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/stripe.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_synch_toc_nav.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/progress.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_print_edit.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/print_edit.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/toc_open.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_hide_nav.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_search_results_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/topic.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/helpbanner.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/forward.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/toc_closed.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/plus.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/synch_toc_nav.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/add_bkmrk.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/search_results_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_bookmarks_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/minus.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/printer.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/back.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/links_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/container_obj.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_links_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/bookmarks_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_forward.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/bookmark_obj.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/separator.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_add_bkmrk.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/banner_prod.jpg
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/tool_separator.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_back.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/images/e_contents_view.gif
plugins/org.eclipse.help.webapp_2.1.0/advanced/nav.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/index.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/toolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/contentToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/highlight.js
plugins/org.eclipse.help.webapp_2.1.0/advanced/banner.html
plugins/org.eclipse.help.webapp_2.1.0/advanced/contentActions.js
plugins/org.eclipse.help.webapp_2.1.0/advanced/bookmarksView.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/list.css
plugins/org.eclipse.help.webapp_2.1.0/advanced/toc.js
plugins/org.eclipse.help.webapp_2.1.0/advanced/list.js
plugins/org.eclipse.help.webapp_2.1.0/advanced/views.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/fheader.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/advanced.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/searchInfocenter.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/help.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/searchView.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/tocToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/search.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/tocView.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/searchToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/workingSet.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/livehelp.js.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/linksView.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/header.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/content.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/tabs.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/bookmarksToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/linksToolbar.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/workingSetManager.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/view.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/err.jsp
plugins/org.eclipse.help.webapp_2.1.0/advanced/tree.css
plugins/org.eclipse.help.webapp_2.1.0/webapp.jar
plugins/org.eclipse.help.webapp_2.1.0/about.html
plugins/org.eclipse.help.webapp_2.1.0/index.jsp
plugins/org.eclipse.help.webapp_2.1.0/plugin.properties
plugins/org.eclipse.help.webapp_2.1.0/plugin.xml
plugins/org.eclipse.ui.workbench_2.1.0
plugins/org.eclipse.ui.workbench_2.1.0/workbench.jar
plugins/org.eclipse.ui.workbench_2.1.0/plugin.properties
plugins/org.eclipse.ui.workbench_2.1.0/plugin.xml
plugins/org.eclipse.ui.workbench_2.1.0/about.html
plugins/org.eclipse.team.cvs.ssh_2.1.0
plugins/org.eclipse.team.cvs.ssh_2.1.0/teamcvsssh.jar
plugins/org.eclipse.team.cvs.ssh_2.1.0/plugin.properties
plugins/org.eclipse.team.cvs.ssh_2.1.0/about.html
plugins/org.eclipse.team.cvs.ssh_2.1.0/plugin.xml
plugins/org.eclipse.team.cvs.ssh_2.1.0/.options
plugins/org.eclipse.ui.workbench.texteditor_2.1.0
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full/ctool16
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full/ctool16/last_edit_pos.gif
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full/etool16
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full/etool16/last_edit_pos.gif
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full/dtool16
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/icons/full/dtool16/last_edit_pos.gif
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/texteditor.jar
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/plugin.xml
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/about.html
plugins/org.eclipse.ui.workbench.texteditor_2.1.0/plugin.properties
plugins/org.eclipse.ui.views_2.1.0
plugins/org.eclipse.ui.views_2.1.0/views.jar
plugins/org.eclipse.ui.views_2.1.0/plugin.properties
plugins/org.eclipse.ui.views_2.1.0/plugin.xml
plugins/org.eclipse.ui.views_2.1.0/about.html
plugins/org.eclipse.ui.editors_2.1.0
plugins/org.eclipse.ui.editors_2.1.0/editors.jar
plugins/org.eclipse.ui.editors_2.1.0/plugin.xml
plugins/org.eclipse.ui.editors_2.1.0/about.html
plugins/org.eclipse.ui.editors_2.1.0/plugin.properties
plugins/org.eclipse.ui_2.1.0
plugins/org.eclipse.ui_2.1.0/icons
plugins/org.eclipse.ui_2.1.0/icons/full
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/defaults_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/up_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/step_current.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/min_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/filter_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showexpert_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/stop_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/step_done.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/scroll_rt.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/refresh_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/pin_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/scrollend.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/synced.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/filter_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/scrollhome.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/gotoobj_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showparents_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showchild_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/selected_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showcomplete_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/view_menu.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/edittsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/list_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/addtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/scroll_lft.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/home_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showerr_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/apply_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/addbkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/alpha_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/remtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/collapseall.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/backward_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/tree_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/forward_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showwarn_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/close_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/popup_menu.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showsync_rn.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/graph_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/rembkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showcategory_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/clcl16/showbasic_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/paste_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/debug_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/delete_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/move_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/quick_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/cut_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/print_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/run_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/redo_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/importzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/export_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/saveas_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/importdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/newfile_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/saveall_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/copy_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/save_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/exportzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/rename_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/import_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/undo_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/exportdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/pin_editor.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/build_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/newfolder_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/new_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/search_src.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/prefs_misc.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dtool16/newprj_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ovr16
plugins/org.eclipse.ui_2.1.0/icons/full/ovr16/link_ovr.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ovr16/linkwarn_ovr.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/bkmrk_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/new_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/editor_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/defaultview_misc.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/default_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/outline_co.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/resource_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/opensame_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/tasks_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/prop_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/filenav_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/cview16/replace_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/redo_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/importzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/export_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/delete_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/importdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/saveas_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/new_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/copy_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/save_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/exportzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/cut_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/import_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/undo_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/exportdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/pin_editor.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/run_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/newfile_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/build_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/newfolder_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/search_src.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/saveall_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/prefs_misc.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/paste_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/debug_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/rename_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/move_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/quick_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/print_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/etool16/newprj_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showbasic_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/home_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/tree_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/filter_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/scrollhome.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/gotoobj_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showexpert_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/scroll_lft.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/min_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/alpha_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/remtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/scroll_rt.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showparents_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/forward_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showcomplete_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showchild_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/stop_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/close_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/list_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showsync_rn.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/popup_menu.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/pin_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showwarn_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/edittsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/scrollend.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/addtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/defaults_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/rembkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/filter_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/selected_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showerr_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/apply_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/view_menu.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/addbkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/up_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/backward_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/showcategory_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/graph_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dlcl16/refresh_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/import_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/undo_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/new_page.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/exportdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/pin_editor.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/build_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/newfolder_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/search_src.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/prev_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/prefs_misc.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/newprj_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/paste_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/debug_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/run_exec.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/next_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/saveas_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/saveall_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/move_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/newfile_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/print_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/save_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/redo_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/importzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/export_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/importdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/new_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/copy_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/rename_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/cut_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/delete_edit.gif
plugins/org.eclipse.ui_2.1.0/icons/full/ctool16/exportzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/tasks_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/prop_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/replace_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/defaultview_misc.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/new_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/filenav_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/resource_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/opensame_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/bkmrk_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/default_persp.gif
plugins/org.eclipse.ui_2.1.0/icons/full/eview16/outline_co.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/incomplete_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/welcome_editor.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/file_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/probmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/header_complete.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/warn_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/warning.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/fldr_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/workset.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/cprj_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/elements_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/complete_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/taskmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/element_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/welcome_banner.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/header_priority.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/system_summary_editor.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/cfldr_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/hprio_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/prj_obj.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/error_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/lprio_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/welcome_item.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/dots_button.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/info_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/obj16/bkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/dnd
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/top_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/left_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/left_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/tofastview_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/tofastview_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/bottom_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/offscreen_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/right_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/bottom_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/invalid_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/stack_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/right_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/offscreen_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/stack_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/invalid_mask.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/dnd/top_source.bmp
plugins/org.eclipse.ui_2.1.0/icons/full/wizban
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/exportzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/saveas_dlg.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/newfile_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/exportdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/import_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/newfolder_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/new_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/importzip_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/newprj_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/importdir_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/export_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/wizban/workset_wiz.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/scroll_lft.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/home_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/apply_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/scrollhome.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/synced.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/alpha_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/remtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/collapseall.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/forward_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showchild_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/close_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showsync_rn.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/popup_menu.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/tree_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/edittsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/addtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/defaults_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showerr_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showtsk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/min_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/up_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showexpert_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showcomplete_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/scrollend.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/addbkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/filter_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/graph_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/stop_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/refresh_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/backward_nav.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/pin_view.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showwarn_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/scroll_rt.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showparents_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/rembkmrk_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/view_menu.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/filter_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showbasic_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/selected_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/list_mode.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/showcategory_ps.gif
plugins/org.eclipse.ui_2.1.0/icons/full/elcl16/gotoobj_tsk.gif
plugins/org.eclipse.ui_2.1.0/icons/full/commands
plugins/org.eclipse.ui_2.1.0/icons/full/commands/exclamation.gif
plugins/org.eclipse.ui_2.1.0/icons/full/commands/change.gif
plugins/org.eclipse.ui_2.1.0/icons/full/commands/blank.gif
plugins/org.eclipse.ui_2.1.0/icons/full/commands/minus.gif
plugins/org.eclipse.ui_2.1.0/icons/full/commands/plus.gif
plugins/org.eclipse.ui_2.1.0/ui.jar
plugins/org.eclipse.ui_2.1.0/plugin.xml
plugins/org.eclipse.ui_2.1.0/plugin.properties
plugins/org.eclipse.ui_2.1.0/.options
plugins/org.eclipse.ui_2.1.0/about.html
plugins/org.eclipse.debug.ui_2.1.0
plugins/org.eclipse.debug.ui_2.1.0/icons
plugins/org.eclipse.debug.ui_2.1.0/icons/full
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/stepinto_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/stepover_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/rem_all_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/clear_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/enabled_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/resume_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/stepreturn_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/metharg_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/stepbystep_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/copy_edit_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/changevariablevalue_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/disabled_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/tnames_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/lock_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/terminate_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/debuglast_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/disconnect_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/rem_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/terminate_all_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/toggledetailpane_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/suspend_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/terminate_rem_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/elcl16/runlast_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/rem_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/resume_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/stepinto_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/stepover_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/changevariablevalue_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/lock_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/toggledetailpane_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/disconnect_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/suspend_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/metharg_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/clear_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/runlast_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/copy_edit_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/rem_all_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/tnames_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/terminate_all_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/enabled_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/disabled_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/terminate_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/terminate_rem_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/stepreturn_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/debuglast_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/clcl16/stepbystep_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/copy_edit_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/disconnect_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/stepinto_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/resume_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/stepover_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/suspend_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/debuglast_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/terminate_all_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/runlast_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/terminate_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/rem_all_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/clear_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/metharg_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/enabled_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/terminate_rem_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/lock_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/stepreturn_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/toggledetailpane_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/tnames_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/stepbystep_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/disabled_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/rem_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dlcl16/changevariablevalue_co.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/thread_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/rundebug.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/threadt_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/stckframe_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/genericvariable_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/osprc_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/lrun_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/inst_ptr_top.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/ldebug_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/brkp_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/expression_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/debugtt_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/terminatedlaunch_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/osprct_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/threads_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/debugt_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/stckframe_running_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/inst_ptr.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/obj16/brkpd_obj.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dtool16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dtool16/run_exc.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/dtool16/debug_exc.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/wizban
plugins/org.eclipse.debug.ui_2.1.0/icons/full/wizban/run_wiz.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/wizban/debug_wiz.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ovr16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ovr16/error.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ovr16/stcksync_ov.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ovr16/transparent.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/variable_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/process_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/watchlist_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/debug_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/breakpoint_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/debug_persp.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/cview16/console_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/console_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/debug_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/debug_persp.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/variable_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/process_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/watchlist_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/eview16/breakpoint_view.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ctool16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ctool16/debug_exc.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/ctool16/run_exc.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/etool16
plugins/org.eclipse.debug.ui_2.1.0/icons/full/etool16/debug_exc.gif
plugins/org.eclipse.debug.ui_2.1.0/icons/full/etool16/run_exc.gif
plugins/org.eclipse.debug.ui_2.1.0/dtui.jar
plugins/org.eclipse.debug.ui_2.1.0/about.html
plugins/org.eclipse.debug.ui_2.1.0/.options
plugins/org.eclipse.debug.ui_2.1.0/plugin.properties
plugins/org.eclipse.debug.ui_2.1.0/plugin.xml
plugins/org.eclipse.compare_2.1.0
plugins/org.eclipse.compare_2.1.0/icons
plugins/org.eclipse.compare_2.1.0/icons/full
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/copy_r_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/copycont_l_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/syncpane_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/copy_l_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/ancestorpane_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/copycont_r_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/prev_nav.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/smartmode_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/twowaycompare_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/clcl16/next_nav.gif
plugins/org.eclipse.compare_2.1.0/icons/full/obj16
plugins/org.eclipse.compare_2.1.0/icons/full/obj16/resource_obj.gif
plugins/org.eclipse.compare_2.1.0/icons/full/obj16/day_obj.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/copycont_r_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/next_nav.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/twowaycompare_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/copy_l_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/syncpane_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/copycont_l_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/smartmode_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/copy_r_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/prev_nav.gif
plugins/org.eclipse.compare_2.1.0/icons/full/elcl16/ancestorpane_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/confchg_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/add_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/inchg_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/outdel_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/r_inadd_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/r_outadd_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/confdel_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/outadd_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/indel_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/chg_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/r_inchg_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/r_outchg_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/error_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/confadd_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/inadd_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/del_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/outchg_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/r_indel_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ovr16/r_outdel_ov.gif
plugins/org.eclipse.compare_2.1.0/icons/full/cview16
plugins/org.eclipse.compare_2.1.0/icons/full/cview16/compare_view.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dtool16
plugins/org.eclipse.compare_2.1.0/icons/full/dtool16/ignorews_edit.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dtool16/conflict_edit.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/prev_nav.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/ancestorpane_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/syncpane_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/copycont_l_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/copy_l_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/next_nav.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/smartmode_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/copycont_r_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/copy_r_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/dlcl16/twowaycompare_co.gif
plugins/org.eclipse.compare_2.1.0/icons/full/etool16
plugins/org.eclipse.compare_2.1.0/icons/full/etool16/conflict_edit.gif
plugins/org.eclipse.compare_2.1.0/icons/full/etool16/ignorews_edit.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ctool16
plugins/org.eclipse.compare_2.1.0/icons/full/ctool16/conflict_edit.gif
plugins/org.eclipse.compare_2.1.0/icons/full/ctool16/ignorews_edit.gif
plugins/org.eclipse.compare_2.1.0/icons/full/eview16
plugins/org.eclipse.compare_2.1.0/icons/full/eview16/compare_view.gif
plugins/org.eclipse.compare_2.1.0/compare.jar
plugins/org.eclipse.compare_2.1.0/plugin.xml
plugins/org.eclipse.compare_2.1.0/plugin.properties
plugins/org.eclipse.compare_2.1.0/about.html
plugins/org.eclipse.update.ui.forms_2.1.0
plugins/org.eclipse.update.ui.forms_2.1.0/forms.jar
plugins/org.eclipse.update.ui.forms_2.1.0/plugin.xml
plugins/org.eclipse.update.ui.forms_2.1.0/about.html
plugins/org.eclipse.update.ui.forms_2.1.0/plugin.properties
plugins/org.eclipse.search_2.1.0
plugins/org.eclipse.search_2.1.0/icons
plugins/org.eclipse.search_2.1.0/icons/full
plugins/org.eclipse.search_2.1.0/icons/full/obj16
plugins/org.eclipse.search_2.1.0/icons/full/obj16/tsearch_dpdn_obj.gif
plugins/org.eclipse.search_2.1.0/icons/full/obj16/tsearch_obj.gif
plugins/org.eclipse.search_2.1.0/icons/full/obj16/searchm_obj.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_rem.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_next.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_prev.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_history.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_stop.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_remall.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_sortmatch.gif
plugins/org.eclipse.search_2.1.0/icons/full/elcl16/search_goto.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_remall.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_stop.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_history.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_goto.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_next.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_prev.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_rem.gif
plugins/org.eclipse.search_2.1.0/icons/full/dlcl16/search_sortmatch.gif
plugins/org.eclipse.search_2.1.0/icons/full/cview16
plugins/org.eclipse.search_2.1.0/icons/full/cview16/searchres.gif
plugins/org.eclipse.search_2.1.0/icons/full/eview16
plugins/org.eclipse.search_2.1.0/icons/full/eview16/searchres.gif
plugins/org.eclipse.search_2.1.0/icons/full/dtool16
plugins/org.eclipse.search_2.1.0/icons/full/dtool16/search.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_goto.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_history.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_remall.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_next.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_prev.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_sortmatch.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_rem.gif
plugins/org.eclipse.search_2.1.0/icons/full/clcl16/search_stop.gif
plugins/org.eclipse.search_2.1.0/icons/full/etool16
plugins/org.eclipse.search_2.1.0/icons/full/etool16/search.gif
plugins/org.eclipse.search_2.1.0/icons/full/ctool16
plugins/org.eclipse.search_2.1.0/icons/full/ctool16/search.gif
plugins/org.eclipse.search_2.1.0/search.jar
plugins/org.eclipse.search_2.1.0/plugin.properties
plugins/org.eclipse.search_2.1.0/about.html
plugins/org.eclipse.search_2.1.0/plugin.xml
plugins/org.eclipse.team.ui_2.1.0
plugins/org.eclipse.team.ui_2.1.0/icons
plugins/org.eclipse.team.ui_2.1.0/icons/full
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/refresh.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/incom_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/catchup_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/outgo_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/contents.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/release_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/catchuprelease_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/site_element.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/ignorews_edit.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/clcl16/conflict_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/contents.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/ignorews_edit.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/incom_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/catchup_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/catchuprelease_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/refresh.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/conflict_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/outgo_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/release_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/dlcl16/site_element.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/ovr
plugins/org.eclipse.team.ui_2.1.0/icons/full/ovr/version_controlled.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/ovr/dirty_ov.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/ovr/checkedout_ov.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/obj
plugins/org.eclipse.team.ui_2.1.0/icons/full/obj/share_project.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/obj/export_projectset.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/obj/import_projectset.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/incom_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/catchup_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/ignorews_edit.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/outgo_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/contents.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/release_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/site_element.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/refresh.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/catchuprelease_rls.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/elcl16/conflict_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/cview16
plugins/org.eclipse.team.ui_2.1.0/icons/full/cview16/synch_synch.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/wizban
plugins/org.eclipse.team.ui_2.1.0/icons/full/wizban/export_projectset_wizban.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/wizban/import_projectset_wizban.gif
plugins/org.eclipse.team.ui_2.1.0/icons/full/wizban/share_wizban.gif
plugins/org.eclipse.team.ui_2.1.0/teamui.jar
plugins/org.eclipse.team.ui_2.1.0/about.html
plugins/org.eclipse.team.ui_2.1.0/plugin.xml
plugins/org.eclipse.team.ui_2.1.0/plugin.properties
plugins/org.eclipse.help.ui_2.1.0
plugins/org.eclipse.help.ui_2.1.0/icons
plugins/org.eclipse.help.ui_2.1.0/icons/workingset.gif
plugins/org.eclipse.help.ui_2.1.0/icons/back.gif
plugins/org.eclipse.help.ui_2.1.0/icons/search_menu.gif
plugins/org.eclipse.help.ui_2.1.0/icons/search_sortmatch.gif
plugins/org.eclipse.help.ui_2.1.0/icons/topic.gif
plugins/org.eclipse.help.ui_2.1.0/icons/forward.gif
plugins/org.eclipse.help.ui_2.1.0/icons/view.gif
plugins/org.eclipse.help.ui_2.1.0/helpworkbench.jar
plugins/org.eclipse.help.ui_2.1.0/about.html
plugins/org.eclipse.help.ui_2.1.0/plugin.properties
plugins/org.eclipse.help.ui_2.1.0/contexts.xml
plugins/org.eclipse.help.ui_2.1.0/.options
plugins/org.eclipse.help.ui_2.1.0/plugin.xml
plugins/org.eclipse.update.ui_2.1.0
plugins/org.eclipse.update.ui_2.1.0/webapp
plugins/org.eclipse.update.ui_2.1.0/webapp/WEB-INF
plugins/org.eclipse.update.ui_2.1.0/webapp/WEB-INF/lib
plugins/org.eclipse.update.ui_2.1.0/webapp/WEB-INF/lib/update-servlets.jar
plugins/org.eclipse.update.ui_2.1.0/webapp/WEB-INF/web.xml
plugins/org.eclipse.update.ui_2.1.0/webapp/images
plugins/org.eclipse.update.ui_2.1.0/webapp/images/backward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/webapp/images/form_banner.jpg
plugins/org.eclipse.update.ui_2.1.0/webapp/images/form_underline.jpg
plugins/org.eclipse.update.ui_2.1.0/icons
plugins/org.eclipse.update.ui_2.1.0/icons/full
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/preview.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/configs.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/selected_updates.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/update_pers.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/updates.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/featuresrc_result.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/eview16/browser.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/tsearch_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/bfolder_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/lsite_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/cd_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/esite_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/web_bkmrk_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/efix2_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/unconf_feature_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/config_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/site_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/saved_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/vremovable_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/vremote_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/usearch_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/vfixed_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/updates_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/history_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/psite_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/notinstalled_feature_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/category_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/floppy_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/computer_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/app_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/efix_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/feature_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/places_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/obj16/psearch_obj.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/uninstall_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/install_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/update_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/new_search_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/config_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/new_folder_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ctool16/new_bookmark_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/featuresrc_result.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/browser.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/update_pers.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/preview.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/configs.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/selected_updates.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/cview16/updates.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/new_bookmark_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/config_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/uninstall_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/new_search_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/new_folder_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/update_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/etool16/install_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/forms
plugins/org.eclipse.update.ui_2.1.0/icons/full/forms/topic.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/forms/def_provider.jpg
plugins/org.eclipse.update.ui_2.1.0/icons/full/forms/form_banner.jpg
plugins/org.eclipse.update.ui_2.1.0/icons/full/forms/form_underline.jpg
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/stop_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/go_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/home_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/refresh_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/show_unconf.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/forward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/collapseall.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/elcl16/backward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/linked_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/warning_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/unconfigured_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/updated_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/current_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/error_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/add_stat.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/mod_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/installable_co.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/ovr16/del_stat.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/new_bookmark_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/new_search_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/config_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/install_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/new_folder_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/def_wizban.jpg
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/update_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/wizban/uninstall_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/new_folder_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/config_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/install_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/uninstall_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/new_bookmark_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/new_search_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dtool16/update_wiz.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/go_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/stop_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/backward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/refresh_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/home_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/show_unconf.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/dlcl16/forward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/go_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/stop_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/refresh_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/show_unconf.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/home_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/forward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/icons/full/clcl16/backward_nav.gif
plugins/org.eclipse.update.ui_2.1.0/updateui.jar
plugins/org.eclipse.update.ui_2.1.0/plugin.xml
plugins/org.eclipse.update.ui_2.1.0/plugin.properties
plugins/org.eclipse.update.ui_2.1.0/about.html
plugins/org.eclipse.ui.externaltools_2.1.0
plugins/org.eclipse.ui.externaltools_2.1.0/lib
plugins/org.eclipse.ui.externaltools_2.1.0/lib/antrunner.jar
plugins/org.eclipse.ui.externaltools_2.1.0/icons
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/task_obj.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/targetpublic_obj.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/main_tab.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/ant.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/invalid_build_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/ant_project_err.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/ttype_program.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/external_tools.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/type.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/property_obj.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/prop_ps.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/options_tab.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/targetprivate_obj.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/ant_buildfile.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/ant_tsk_arrow.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/classpath.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/element.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/defaulttarget_obj.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/builder.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/jar_l_obj.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/ant_target_err.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/obj16/elements.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/eview16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/eview16/external_tools.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/activate.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/deactivate.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/refresh.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/properties.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/search.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/gotoobj_tsk.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/add_co.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/moveUp.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/moveDown.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/ant_targets.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/removeAll_co.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/remove_co.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/clcl16/run_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/th_single.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/new_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/th_horizontal.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/copy_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/run_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/del_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/rename_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/refresh.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/runwith_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/paste_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/th_vertical.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dlcl16/prop_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/run_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/refresh.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/del_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/paste_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/copy_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/th_horizontal.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/rename_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/runwith_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/prop_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/new_tool.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/th_vertical.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/elcl16/th_single.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dtool16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/dtool16/external_tools.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/wizban
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/wizban/ext_tools_wiz.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/ctool16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/ctool16/external_tools.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/cview16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/cview16/ant_view.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/etool16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/etool16/external_tools.gif
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/ovr16
plugins/org.eclipse.ui.externaltools_2.1.0/icons/full/ovr16/error_co.gif
plugins/org.eclipse.ui.externaltools_2.1.0/externaltools.jar
plugins/org.eclipse.ui.externaltools_2.1.0/plugin.properties
plugins/org.eclipse.ui.externaltools_2.1.0/about.html
plugins/org.eclipse.ui.externaltools_2.1.0/plugin.xml
plugins/org.eclipse.ui.externaltools_2.1.0/.options
plugins/org.eclipse.team.cvs.ui_2.1.0
plugins/org.eclipse.team.cvs.ui_2.1.0/icons
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/dlcl16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/dlcl16/clear_co.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/dlcl16/refresh.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/dlcl16/filter_history.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizban
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizban/newconnect_wizban.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizban/keywordsub_wizban.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizban/newlocation_wizban.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizban/createpatch_wizban.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizban/mergestream_wizban.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/cview16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/cview16/cvs_persp.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/cview16/rep_editors_view.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/cview16/console_view.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/cview16/history_view.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/cview16/repo_rep.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/dtool16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/dtool16/contents.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/elcl16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/elcl16/filter_history.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/elcl16/refresh.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/elcl16/collapseall.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/elcl16/clear_co.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph2.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph5.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph1.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph8.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph4.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph7.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph3.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/glyphs/glyph6.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16/versions_rep.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16/module_rep.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16/tag.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16/repository_rep.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16/branches_rep.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/obj16/prjversions_rep.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/clcl16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/clcl16/filter_history.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/clcl16/newstream_wiz.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/clcl16/collapseall.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/clcl16/clear_co.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/clcl16/refresh.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ctool16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ctool16/contents.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ctool16/checkout.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ovr16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ovr16/merged_ov.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ovr16/no_remotedir_ov.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ovr16/confauto_ov.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ovr16/question_ov.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/ovr16/edited_ov.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizards
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizards/newlocation_wiz.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizards/newconnect_wiz.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/wizards/cvs_synch.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/etool16
plugins/org.eclipse.team.cvs.ui_2.1.0/icons/full/etool16/contents.gif
plugins/org.eclipse.team.cvs.ui_2.1.0/teamcvsui.jar
plugins/org.eclipse.team.cvs.ui_2.1.0/plugin.properties
plugins/org.eclipse.team.cvs.ui_2.1.0/about.html
plugins/org.eclipse.team.cvs.ui_2.1.0/plugin.xml
plugins/org.eclipse.platform.linux.gtk_2.1.0
plugins/org.eclipse.platform.linux.gtk_2.1.0/plugin.properties
plugins/org.eclipse.platform.linux.gtk_2.1.0/about.properties
plugins/org.eclipse.platform.linux.gtk_2.1.0/eclipse32.gif
plugins/org.eclipse.platform.linux.gtk_2.1.0/plugin.xml
plugins/org.eclipse.platform.linux.gtk_2.1.0/about.ini
plugins/org.eclipse.platform.linux.gtk_2.1.0/about.mappings
plugins/org.eclipse.platform.linux.gtk_2.1.0/about.html
plugins/org.eclipse.swt.gtk_2.1.0
plugins/org.eclipse.swt.gtk_2.1.0/ws
plugins/org.eclipse.swt.gtk_2.1.0/ws/gtk
plugins/org.eclipse.swt.gtk_2.1.0/ws/gtk/swt-pi.jar
plugins/org.eclipse.swt.gtk_2.1.0/ws/gtk/swt.jar
plugins/org.eclipse.swt.gtk_2.1.0/os
plugins/org.eclipse.swt.gtk_2.1.0/os/linux
plugins/org.eclipse.swt.gtk_2.1.0/os/linux/x86
plugins/org.eclipse.swt.gtk_2.1.0/os/linux/x86/libswt-gnome-gtk-2133.so
plugins/org.eclipse.swt.gtk_2.1.0/os/linux/x86/libswt-pi-gtk-2133.so
plugins/org.eclipse.swt.gtk_2.1.0/os/linux/x86/libswt-gtk-2133.so
plugins/org.eclipse.swt.gtk_2.1.0/fragment.properties
plugins/org.eclipse.swt.gtk_2.1.0/lgpl-v21.txt
plugins/org.eclipse.swt.gtk_2.1.0/about.html
plugins/org.eclipse.swt.gtk_2.1.0/fragment.xml
plugins/org.eclipse.swt.gtk_2.1.0/cpl-v10.html
plugins/org.eclipse.core.resources.linux_2.1.0
plugins/org.eclipse.core.resources.linux_2.1.0/os
plugins/org.eclipse.core.resources.linux_2.1.0/os/linux
plugins/org.eclipse.core.resources.linux_2.1.0/os/linux/x86
plugins/org.eclipse.core.resources.linux_2.1.0/os/linux/x86/libcore_2_1_0a.so
plugins/org.eclipse.core.resources.linux_2.1.0/fragment.xml
plugins/org.eclipse.update.core.linux_2.1.0
plugins/org.eclipse.update.core.linux_2.1.0/about.html
plugins/org.eclipse.update.core.linux_2.1.0/fragment.xml
features/org.eclipse.platform_2.1.0
features/org.eclipse.platform_2.1.0/feature.xml
features/org.eclipse.platform_2.1.0/eclipse_update_120.jpg
features/org.eclipse.platform_2.1.0/license.html
features/org.eclipse.platform_2.1.0/feature.properties
features/org.eclipse.platform_2.1.0/cpl-v10.html
features/org.eclipse.platform.linux.gtk_2.1.0
features/org.eclipse.platform.linux.gtk_2.1.0/cpl-v10.html
features/org.eclipse.platform.linux.gtk_2.1.0/feature.properties
features/org.eclipse.platform.linux.gtk_2.1.0/feature.xml
features/org.eclipse.platform.linux.gtk_2.1.0/license.html
features/org.eclipse.platform.linux.gtk_2.1.0/eclipse_update_120.jpg
"

base_files="
plugins
features
icon.xpm
eclipse
startup.jar
"
