Hello %R, there are %N (max %M) users logged in at the moment.
Local time is: %T

Please use your email address as password and NOT silly words
like "mozilla@" or "WWWuser@", as some Web browsers do!

If you have any questions concerning this ftp archive or would
like to announce your uploads, please send a mail to the ftp-admin
of this server: %E

All transfers are logged. If you don't like this, disconnect now.
