define(`confCCOPTS', `@@confCCOPTS@@')
define(`confMAPDEF', `@@confMAPDEF@@')
define(`confENVDEF', `@@confENVDEF@@')
define(`confLIBS', `@@confLIBS@@')
define(`confSTDIO_TYPE', `portable')
define(`confLDOPTS', `-s')
define(`confMANOWN', `root')
define(`confMANGRP', `root')
define(`confMANMODE', `644')
define(`confMAN1SRC', `1')
define(`confMAN5SRC', `5')
define(`confMAN8SRC', `8')
define(`confLDOPTS_SO', `-shared -Wl')
APPENDDEF(`conf_sendmail_LIBS', `@@conf_sendmail_LIBS@@')
