# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

MODULE_AUTHOR="JJSCHUTZ"
inherit perl-module

DESCRIPTION="Sphinx search engine configuration file read/modify/write"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~ppc ~ppc64 ~x86"

DEPEND="dev-lang/perl"
