# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/functest/functest-0.8.8.ebuild,v 1.3 2009/07/27 07:14:37 mr_bones_ Exp $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI="2"
inherit distutils

DESCRIPTION="Functest is a test tool/framework for testing in python"
HOMEPAGE="http://code.google.com/p/functest/"
SRC_URI="http://cheeseshop.python.org/packages/source/${PN:0:1}/${PN}/${P}.tar.gz"
LICENSE="Apache-2.0"
KEYWORDS="~x86"
SLOT="0"
IUSE="test"
DEPEND="dev-python/setuptools
		virtual/python
		test? ( >=dev-python/nose-0.10.4 )"
RDEPEND="${DEPEND}"

src_test(){
	PYTHONPATH=. nosetests || die "Test failed"
}
