#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/net-firewall/ipkungfu/files/ipkungfu.init,v 1.1 2003/08/31 20:32:52 weeve Exp $

depend() {
	need logger net
}

start () {
	ebegin "Starting ipkungfu"
	/usr/sbin/ipkungfu --init
	eend $? "Failed to start ipkungfu"
}

stop() {
	ebegin "Stopping ipkungfu"
	/usr/sbin/ipkungfu --disable
	eend $? "Failed to stop ipkungfu"
}
