.\" This manual is published under the GPL.
.\" All guidelines specified in the GPL apply here.
.\" To get an ascii file:
.\" groff -man -Tascii pon.1 > pon.txt
.\"
.TH PON 1 "February 2000" "Debian Project" "Debian PPPD"
.SH NAME
pon, poff, plog \- starts up, shuts down or lists the log of PPP connections
.SH SYNOPSIS
.B pon
.RB [ " isp-name " ]
.br
.B poff
.RB [ " \-r " ]
.RB [ " \-d " ]
.RB [ " \-c " ]
.RB [ " \-a " ]
.RB [ " \-h " ]
.B isp-name
.br
.B plog
.RB [ " argument " ]
.SH DESCRIPTION
This manual page describes the \fBpon\fP, \fBpoff\fP and \fBplog\fP
scripts, which allow users to control PPP connections.
.PP
.B pon
starts a PPP connection to a provider, reading its configuration from
.I /etc/ppp/peers/provider
and using the chatscript
.IR /etc/chatscripts/provider .
This is the default setting if
.B isp-name
is not given.
.PP
To start a PPP connection to a different provider, specify an
.B isp-name
operand.  For instance, to use provider configuration "provider2" run
.IP 
pon provider2 
.PP
The system will then use the chatscript
.I /etc/chatscripts/provider2
and the options file
.IR "/etc/ppp/peers/provider2".
You can use
.B pon
to run multiple, simultaneous PPP connections.
.PP
.B poff
closes a PPP connection. If more than one PPP connection exists, the one named
in the argument to 
.B poff 
will be killed, e.g. 
.IP 
poff myprovider2
.PP
will terminate the connection to myprovider2, and leave the PPP connection 
to "myprovider1" up and running.
.PP
.B plog
shows you the last few lines of
.IR /var/log/ppp.log .
If that file doesn't exist, it shows you the last few lines of
.IR /var/log/syslog
file, but excluding the lines not generated by pppd.
This script makes use of the
.BR tail (1)
command, so arguments that can be passed to
.BR tail (1)
can also be passed to 
.B plog.
.SH OPTIONS
.SS Options for pon
.TP
.B isp-name
is the name of the ISP connection to start. If no
.B isp-name
is specified,
.B pon
will use the name "provider".
.SS Options for poff
.TP
.B "\-r"
causes the connection to be redialed after it is dropped.
.TP
.B "\-d"
toggles the state of pppd's debug option.
.TP
.B "\-c"
causes
.BR pppd (8)
to renegotiate compression.
.TP
.B "\-a"
stops all running ppp connections. If the argument
.B isp-name
is given it will be ignored.
.TP
.B "\-h"
displays help information.
.TP
.B "\-v"
prints the version and exits.
.PP
If no argument is given it will kill all ppp connections. Like the
.B "\-a"
option.
.SS Options for plog
.TP
.B argument
is any argument you can also pass to
.BR tail (1).
.SH REQUIREMENTS
.BR pppd (8)
must be installed and configured.
.PP
.I /etc/chatscripts/provider
is the default chatscript, used when
.B pon
is invoked without an argument. Edit it to suit your needs. See
.BR chat (8).
.PP
.I /etc/ppp/peers/provider
is the default options file, used when
.B pon
is invoked without an argument. Edit it to suit your needs. See
.BR pppd (8).
.PP
When
.B pon
is invoked with an
.B isp-name
argument, different filenames are used.  For example, if
.B isp-name
"myprovider" is specified, chatscript
.I /etc/chatscripts/myprovider
and options file
.IR /etc/ppp/peers/myprovider
are used.
.SH NOTE
The
.B plog
script can only be used by root or another system administrator in
group "adm" due to security reasons. Also, to have all pppd-generated
information in one logfile, that plog can show, you need the following
line in your /etc/syslog.conf file:
.PP
local2.*		-/var/log/ppp.log
.SH FILES
.TP
.I /etc/chatscripts/provider
The default chat script.
.TP
.I /etc/ppp/peers/provider
The default peer option file.
.TP
.I /etc/ppp/chap-secrets
System CHAP passwords file.
.TP
.I /etc/ppp/pap-secrets
System PAP passwords file.
.TP
.I /etc/ppp/options
System PPP option file.
.TP
.I /var/log/ppp.log
The default PPP log file.
.SH AUTHORS
The p-commands were written by Christoph Lameter <clameter@debian.org>.
Updated and revised by Philip Hands <phil@hands.com>.
.br
This manual was written by Othmar Pasteka <othmar@tron.at> and modified
by Rob Levin <lilo@openprojects.net>, with some extensions taken from the
old p-commands manual written by John Hasler <jhasler@debian.org>.
.SH "SEE ALSO"
.BR chat (8),
.BR pppd (8),
.BR tail (1).
