# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="4"

MODULE_AUTHOR="DCONWAY"

inherit perl-module

SRC_TEST="do"

DESCRIPTION="Support for creating standard "inside-out" classes"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE="test"

RDEPEND="virtual/perl-Data-Dumper
	virtual/perl-Scalar-List-Utils"

DEPEND="${RDEPEND}
	virtual/perl-Module-Build
	test? ( virtual/perl-Test-Simple )"
