#!/sbin/runscript
# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/trafd/files/trafd.init,v 1.3 2006/11/16 20:46:55 cedk Exp $

depend() {
	need net
	use cupsd
}

start() {
	ebegin "Starting trafd"
	/usr/bin/trafd -p -r -i ${IFACE}
	result=$?
	eend $result
}

stop() {
	ebegin "Stopping trafd"
	/usr/bin/trafstop ${IFACE} > /dev/null
	result=$?
	eend $result
}
