#!/sbin/runscript
# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/trafd/files/trafd.init,v 1.1 2002/11/08 13:07:26 aliz Exp $

depend() {
	need net
	use cupsd
}

start() {
	ebegin "Starting trafd"
	/usr/bin/trafd -p -r -i eth0
	result=$?
	eend $result
}

stop() {
	ebegin "Stopping trafd"
	/usr/bin/trafstop eth0 > /dev/null
	result=$?
	eend $result
}
