# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/bitkeeper/bitkeeper-3.0-r1.ebuild,v 1.7 2003/07/18 20:20:45 vapier Exp $

DESCRIPTION="BitKeeper is a scalable configuration management system."
SRC_URI="x86? ( bk-${PV}-x86-glibc22-linux.bin )
	ppc? ( bk-${PV}-powerpc-glibc21-linux.bin )
	sparc? ( bk-${PV}-sparc-glibc21-linux.bin )
	alpha? ( bk-${PV}-alpha-glibc21-linux.bin )"
HOMEPAGE="http://www.bitkeeper.com"

SLOT="0"
LICENSE="BKL"
KEYWORDS="x86 ppc sparc alpha"
RESTRICT="fetch"

DEPEND="virtual/glibc
	>=dev-lang/tcl-8.3.3
	X? ( >=dev-lang/tk-8.3.3 )"

pkg_nofetch() {
	einfo "You need to perform the following steps to install this package:"
	einfo "- Sign up at ${HOMEPAGE}"
	einfo "- Check your mail and visit the download location"
	einfo "- Download ${A} and place it in ${DISTDIR}"
	einfo "- emerge this package again"
}

src_unpack() {
	mkdir ${S}
	cp ${DISTDIR}/${A} ${S}/${A}
	chmod 755 ${S}/${A}
	echo 'none' | ${S}/${A} > ${S}/output 2>/dev/null
	installer=`sed -n -e "s/Installation script: \(.*\)/\1/p" ${S}/output`
	archive=`sed -n -e "s/Gzipped tar archive: \(.*\)/\1/p" ${S}/output`
	mv $installer ${S}/installer
	mv $archive ${S}/archive
}

src_install() {
	dodir /opt /etc/env.d
	cd ${D}/opt && tar -xzpf ${S}/archive
	mv ${D}/opt/bitkeeper ${D}/opt/${P}
	chown -R root:root ${D}/opt/${P}
	chmod -R u+w,go-w ${D}/opt/${P}
	cat <<EOF >${D}/etc/env.d/10bitkeeper
# Generated by ${P}.ebuild
PATH=/opt/${P}
ROOTPATH=/opt/${P}
MANPATH=/opt/${P}/man
EOF
}

pkg_postinst() {
	einfo "Run 'bk regressions' to verify the installation. (Recommended)"
}
