#!/usr/bin/env /usr/lib/portage/bin/python

import sys
import portage
import string
import os

myroot=portage.getsetting("ROOT")
for x in sys.argv[1:]:
	mysplit=string.split(x,"/")
	portage.unmerge(myroot,mysplit[0],mysplit[1])

