#!/sbin/runscript
#
#

depend() {
	need net
}

start() {
	if [ "${CHECK}" = "YES" ] ; then
	
	    ebegin "Starting ccXstream"
	    start-stop-daemon --start --quiet --exec ${BIN} \
	    -- ${PARAMS} -C ${SERVERCOMMENT}
	    eend $?
	else
	    eerror "Please setup /etc/conf.d/ccxstream before starting ccXstream"
	    
	    return 1
	fi
}

stop() {
        ebegin "Stopping ccXstream"
	start-stop-daemon --stop --quiet --pidfile /var/run/ccxstream.pid
	eend $?
}
