# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="4"

MODULE_AUTHOR="SHLOMIF"

inherit perl-module

SRC_TEST="do"

DESCRIPTION="Perl extension for 32 bit Jenkins Hashing Algorithm"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""
