#!/bin/bash
#
# distcc-config - helper script for distcc and distccd
#
# Copyright 2003 Superlucidity Services, LLC 
# This program licensed under the GNU GPL version 2.
#
# This script developed by Zachary T Welch at Superlucidity Services, LLC
#  based on ideas from irc discussion and the clear need for this support
# 
# Additional features to come; this provides a starting point

# this should be getopt'd someday
DCCC_VERBOSE=1

dccc_echo() {
	[ -n "${DCCC_VERBOSE}" ] && echo "$*"
}

###
# the following functions manage the distcc symlinks
#  they allow the user or other scripts (namely gcc-config) to
#  automatically update distcc's links when upgrading toolchains
#
dccc_remove_link() {
	local t="/usr/lib/distcc/bin/${1}"
	if [ -L ${t} ]; then
		dccc_echo "Removing ${t}..."
		rm -f "${t}"
	fi
}
dccc_install_link() {
	# Search the PATH for the specified compiler
	#  then create shadow link in /usr/lib/distcc/bin to distcc
	if [ -n "$(type -p ${1})" ]; then 
		# first be sure any old link is removed
		DCCC_VERBOSE="" dccc_remove_link "${1}"

		# then create the new link
		local t="/usr/lib/distcc/bin/${1}"
		dccc_echo "Creating distcc shadow link: ${t}..."
		ln -s /usr/bin/distcc "${t}"
	fi
}
dccc_links() {
	local a
	for a in gcc cc c++ g++ ; do
		[ -n "${2}" ] && a="${2}-${a}"
		eval "dccc_${1}_link" "${a}"
	done
}

###
# main routine

case "${1}" in
	--install-links )
		dccc_links install "${2}"
		;;
	--remove-links )
		dccc_links remove "${2}"
		;;
	* )
		echo "usage: ${0} {--install-links|--remove-links} [ CHOST ]"
		;;
esac

