#!/sbin/runscript
# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: 

depend() {
	need net
}

start() {
	ebegin "Starting DansGuardian"
	start-stop-daemon --start --quiet --pidfile /var/run/dansguardian.pid \
			 --exec /usr/sbin/dansguardian
	eend $?
}

stop() {
	ebegin "Stopping DansGuardian"
	start-stop-daemon --stop --quiet --pidfile /var/run/dansguardian.pid
	eend $?
}
