#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-i18n/iiimsf/files/iiim.initd,v 1.2 2004/07/14 21:25:44 agriffis Exp $

start() {
	ebegin "Starting iiim"
	start-stop-daemon -b --start --quiet --exec /usr/lib/im/htt
	eend $?
}

stop() {
	ebegin "Stopping iiim"
	start-stop-daemon --stop --quiet --exec /usr/lib/im/htt
	eend $?
}
