#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-i18n/iiimsf/files/iiim.initd,v 1.1 2003/09/14 00:31:39 usata Exp $

start() {
	ebegin "Starting iiim"
	start-stop-daemon -b --start --quiet --exec /usr/lib/im/htt
	eend $?
}

stop() {
	ebegin "Stopping iiim"
	start-stop-daemon --stop --quiet --exec /usr/lib/im/htt
	eend $?
}
