#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-dotnet/xsp/files/1.1.13/xsp.initd,v 1.1 2006/10/27 13:40:34 jurek Exp $

depend() {
	need net
	after dotnet
}

start() {
	ebegin "Starting xsp"

	start-stop-daemon --quiet --start \
		--background \
		--make-pidfile \
		--pidfile /var/run/aspnet/xsp.pid \
		--chuid aspnet \
		--exec /usr/bin/mono /usr/lib/xsp/1.0/xsp.exe -- --root ${MonoServerRoot} --port ${MonoServerPort} --nonstop
	eend $?
}

stop() {
	ebegin "Stopping xsp"
	start-stop-daemon -o --quiet --stop \
		--pidfile /var/run/aspnet/xsp.pid
	eend $?
}

