# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

MODULE_AUTHOR="PAJAS"

inherit perl-module

DESCRIPTION="a fast builder of compact tree structures from XML documents"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"

DEPEND=">=dev-perl/XML-LibXML-1.69"

SRC_TEST="do"
