#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/dev-db/mysql/files/mysql.init,v 1.4 2003/02/14 22:39:53 vapier Exp $

depend() {
	need net
	use dns
}

checkconfig() {
	if [ ! -f /etc/mysql/my.cnf ] ; then
		eerror "No /etc/mysql/my.cnf file exists!"
	fi

	dir=`awk '{ if ( $0 ~ /^datadir[ \t]+=/ ) { print $3 } }' < /etc/mysql/my.cnf`

	if [ ! -d $dir/mysql ] ; then
		eerror "You dont appear to have the mysql database installed yet."
		eerror "Please run /usr/bin/mysql_install_db to have this done..."
		return 1
	fi
}

start() {
	checkconfig || return 1
	ebegin "Starting mysqld"
	/usr/bin/safe_mysqld >/dev/null 2>&1 &
	eend $?
}

stop () {
	ebegin "Stopping mysqld"
	start-stop-daemon --stop --quiet \
		--pidfile=/var/run/mysqld/mysqld.pid --retry 20
	eend $?
}
