#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/sys-apps/collectl/files/collectl.initd,v 1.2 2009/11/15 01:29:22 vapier Exp $

start() {
	ebegin "Starting collectl"
	start-stop-daemon \
		--start \
		--pidfile /var/run/collectl.pid \
		--exec /usr/bin/collectl -- -D
	eend $?
}

stop() {
	ebegin "Stopping collectl"
	start-stop-daemon --stop --pidfile /var/run/collectl.pid
	eend $?
}
