#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-proxy/bfilter/files/bfilter.init,v 1.1 2005/09/19 05:35:35 mrness Exp $

depend() {
	need net
}

start() {
	ebegin "Starting bfilter"
	start-stop-daemon --start --quiet --exec /usr/bin/bfilter -- ${BFILTER_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping bfilter"
	start-stop-daemon --stop --quiet --exec /usr/bin/bfilter
	eend $?
}
