/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86 1
#define CONFIG_ISA 1
#undef  CONFIG_SBUS
#define CONFIG_UID16 1
/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_MODVERSIONS
#define CONFIG_KMOD 1
/*
 * Processor type and features
 */
#undef  CONFIG_M386
#undef  CONFIG_M486
#undef  CONFIG_M586
#undef  CONFIG_M586TSC
#undef  CONFIG_M586MMX
#undef  CONFIG_M686
#define CONFIG_M686FXSR 1
#undef  CONFIG_MPENTIUM4
#undef  CONFIG_MK6
#undef  CONFIG_MK7
#undef  CONFIG_MCRUSOE
#undef  CONFIG_MWINCHIPC6
#undef  CONFIG_MWINCHIP2
#undef  CONFIG_MWINCHIP3D
#define CONFIG_X86_WP_WORKS_OK 1
#define CONFIG_X86_INVLPG 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_X86_BSWAP 1
#define CONFIG_X86_POPAD_OK 1
#define CONFIG_X86_L1_CACHE_SHIFT (5)
#define CONFIG_X86_TSC 1
#define CONFIG_X86_GOOD_APIC 1
#define CONFIG_X86_PGE 1
#define CONFIG_X86_USE_PPRO_CHECKSUM 1
#define CONFIG_X86_FXSR 1
#define CONFIG_X86_XMM 1
#undef  CONFIG_TOSHIBA
#undef  CONFIG_MICROCODE
#undef  CONFIG_X86_MSR
#undef  CONFIG_X86_CPUID
#define CONFIG_NOHIGHMEM 1
#undef  CONFIG_HIGHMEM4G
#undef  CONFIG_HIGHMEM64G
#define CONFIG_MTRR 1
#undef  CONFIG_SMP
#define CONFIG_X86_UP_IOAPIC 1
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_LOCAL_APIC 1
/*
 * General setup
 */
#define CONFIG_NET 1
#undef  CONFIG_VISWS
#define CONFIG_PCI 1
#undef  CONFIG_PCI_GOBIOS
#undef  CONFIG_PCI_GODIRECT
#define CONFIG_PCI_GOANY 1
#define CONFIG_PCI_BIOS 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_PCI_NAMES 1
#undef  CONFIG_EISA
#undef  CONFIG_MCA
#define CONFIG_HOTPLUG 1
/*
 * PCMCIA/CardBus support
 */
#define CONFIG_PCMCIA 1
#define CONFIG_CARDBUS 1
#undef  CONFIG_I82365
#undef  CONFIG_TCIC
#define CONFIG_SYSVIPC 1
#undef  CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#define CONFIG_KCORE_ELF 1
#undef  CONFIG_KCORE_AOUT
#define CONFIG_BINFMT_AOUT 1
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC 1
#define CONFIG_PM 1
#undef  CONFIG_ACPI
#define CONFIG_APM 1
#undef  CONFIG_APM_IGNORE_USER_SUSPEND
#undef  CONFIG_APM_DO_ENABLE
#undef  CONFIG_APM_CPU_IDLE
#undef  CONFIG_APM_DISPLAY_BLANK
#undef  CONFIG_APM_RTC_IS_GMT
#undef  CONFIG_APM_ALLOW_INTS
#define CONFIG_APM_REAL_MODE_POWER_OFF 1
/*
 * Memory Technology Devices (MTD)
 */
#undef  CONFIG_MTD
/*
 * Parallel port support
 */
#undef  CONFIG_PARPORT
#define CONFIG_PARPORT_MODULE 1
#undef  CONFIG_PARPORT_PC
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_FIFO 1
#undef  CONFIG_PARPORT_PC_SUPERIO
#undef  CONFIG_PARPORT_AMIGA
#undef  CONFIG_PARPORT_MFC3
#undef  CONFIG_PARPORT_ATARI
#undef  CONFIG_PARPORT_SUNBPP
#undef  CONFIG_PARPORT_OTHER
#define CONFIG_PARPORT_1284 1
/*
 * Plug and Play configuration
 */
#define CONFIG_PNP 1
#undef  CONFIG_ISAPNP
#define CONFIG_ISAPNP_MODULE 1
/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD 1
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#define CONFIG_BLK_CPQ_DA_MODULE 1
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_BLK_DEV_DAC960
#define CONFIG_BLK_DEV_DAC960_MODULE 1
#define CONFIG_BLK_DEV_LOOP 1
#undef  CONFIG_BLK_DEV_NBD
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_SIZE (4096)
#define CONFIG_BLK_DEV_INITRD 1
/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#undef  CONFIG_MD_LINEAR
#define CONFIG_MD_LINEAR_MODULE 1
#undef  CONFIG_MD_RAID0
#define CONFIG_MD_RAID0_MODULE 1
#undef  CONFIG_MD_RAID1
#define CONFIG_MD_RAID1_MODULE 1
#undef  CONFIG_MD_RAID5
#define CONFIG_MD_RAID5_MODULE 1
#define CONFIG_BLK_DEV_LVM 1
#define CONFIG_LVM_PROC_FS 1
/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef  CONFIG_PACKET_MMAP
#define CONFIG_NETLINK 1
#define CONFIG_RTNETLINK 1
#undef  CONFIG_NETLINK_DEV
#define CONFIG_NETLINK_DEV_MODULE 1
#define CONFIG_NETFILTER 1
#undef  CONFIG_NETFILTER_DEBUG
#undef  CONFIG_FILTER
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_RTNETLINK 1
#define CONFIG_NETLINK 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef  CONFIG_IP_ROUTE_FWMARK
#define CONFIG_IP_ROUTE_NAT 1
#define CONFIG_IP_ROUTE_MULTIPATH 1
#define CONFIG_IP_ROUTE_TOS 1
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef  CONFIG_IP_ROUTE_LARGE_TABLES
#undef  CONFIG_IP_PNP
#undef  CONFIG_NET_IPIP
#undef  CONFIG_NET_IPGRE
#define CONFIG_IP_MROUTE 1
#undef  CONFIG_IP_PIMSM_V1
#undef  CONFIG_IP_PIMSM_V2
#undef  CONFIG_ARPD
#undef  CONFIG_INET_ECN
#undef  CONFIG_SYN_COOKIES
/*
 *   IP: Netfilter Configuration
 */
#undef  CONFIG_IP_NF_CONNTRACK
#undef  CONFIG_IP_NF_QUEUE
#undef  CONFIG_IP_NF_IPTABLES
#undef  CONFIG_IP_NF_COMPAT_IPCHAINS
#undef  CONFIG_IP_NF_COMPAT_IPFWADM
#define CONFIG_IPV6 1
#undef  CONFIG_IPV6_EUI64
/*
 *   IPv6: Netfilter Configuration
 */
#undef  CONFIG_IP6_NF_IPTABLES
#undef  CONFIG_KHTTPD
#define CONFIG_KHTTPD_MODULE 1
#undef  CONFIG_ATM
/*
 *  
 */
#undef  CONFIG_IPX
#undef  CONFIG_ATALK
#undef  CONFIG_DECNET
#undef  CONFIG_BRIDGE
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL
/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED
/*
 * Telephony Support
 */
#undef  CONFIG_PHONE
/*
 * ATA/IDE/MFM/RLL support
 */
#define CONFIG_IDE 1
/*
 * IDE, ATA and ATAPI Block devices
 */
#define CONFIG_BLK_DEV_IDE 1
/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_HD
#define CONFIG_BLK_DEV_IDEDISK 1
#undef  CONFIG_IDEDISK_MULTI_MODE
#undef  CONFIG_BLK_DEV_IDEDISK_VENDOR
#undef  CONFIG_BLK_DEV_COMMERIAL
#undef  CONFIG_BLK_DEV_IDECS
#define CONFIG_BLK_DEV_IDECD 1
#undef  CONFIG_BLK_DEV_IDETAPE
#define CONFIG_BLK_DEV_IDETAPE_MODULE 1
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#define CONFIG_BLK_DEV_IDEFLOPPY_MODULE 1
#undef  CONFIG_BLK_DEV_IDESCSI
/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_BLK_DEV_CMD640 1
#undef  CONFIG_BLK_DEV_CMD640_ENHANCED
#define CONFIG_BLK_DEV_RZ1000 1
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef  CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_IDEDMA_PCI_AUTO 1
#define CONFIG_BLK_DEV_IDEDMA 1
#undef  CONFIG_IDEDMA_PCI_WIP
#define CONFIG_BLK_DEV_AEC62XX 1
#undef  CONFIG_AEC62XX_TUNING
#define CONFIG_BLK_DEV_ALI15X3 1
#undef  CONFIG_WDC_ALI15X3
#define CONFIG_BLK_DEV_AMD7409 1
#define CONFIG_BLK_DEV_CMD64X 1
#define CONFIG_BLK_DEV_CY82C693 1
#define CONFIG_BLK_DEV_CS5530 1
#define CONFIG_BLK_DEV_HPT34X 1
#define CONFIG_BLK_DEV_HPT366 1
#define CONFIG_BLK_DEV_PIIX 1
#define CONFIG_PIIX_TUNING 1
#define CONFIG_BLK_DEV_NS87415 1
#define CONFIG_BLK_DEV_OPTI621 1
#define CONFIG_BLK_DEV_PDC202XX 1
#undef  CONFIG_PDC202XX_BURST
#define CONFIG_BLK_DEV_OSB4 1
#define CONFIG_BLK_DEV_SIS5513 1
#define CONFIG_BLK_DEV_SLC90E66 1
#define CONFIG_BLK_DEV_TRM290 1
#define CONFIG_BLK_DEV_VIA82CXXX 1
#define CONFIG_IDE_CHIPSETS 1
/*
 * Note: most of these also require special kernel boot parameters
 */
#define CONFIG_BLK_DEV_4DRIVES 1
#define CONFIG_BLK_DEV_ALI14XX 1
#define CONFIG_BLK_DEV_DTC2278 1
#define CONFIG_BLK_DEV_HT6560B 1
#define CONFIG_BLK_DEV_PDC4030 1
#define CONFIG_BLK_DEV_QD6580 1
#define CONFIG_BLK_DEV_UMC8672 1
#define CONFIG_IDEDMA_AUTO 1
#define CONFIG_IDEDMA_IVB 1
#undef  CONFIG_DMA_NONPCI
#define CONFIG_BLK_DEV_IDE_MODES 1
/*
 * SCSI support
 */
#define CONFIG_SCSI 1
/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_SD_EXTRA_DEVS (40)
#undef  CONFIG_CHR_DEV_ST
#define CONFIG_CHR_DEV_ST_MODULE 1
#undef  CONFIG_CHR_DEV_OSST
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR 1
#undef  CONFIG_BLK_DEV_SR_VENDOR
#define CONFIG_SR_EXTRA_DEVS (2)
#undef  CONFIG_CHR_DEV_SG
/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef  CONFIG_SCSI_DEBUG_QUEUES
#undef  CONFIG_SCSI_MULTI_LUN
#undef  CONFIG_SCSI_CONSTANTS
#undef  CONFIG_SCSI_LOGGING
/*
 * SCSI low-level drivers
 */
#undef  CONFIG_BLK_DEV_3W_XXXX_RAID
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#undef  CONFIG_SCSI_7000FASST
#define CONFIG_SCSI_7000FASST_MODULE 1
#undef  CONFIG_SCSI_ACARD
#define CONFIG_SCSI_ACARD_MODULE 1
#undef  CONFIG_SCSI_AHA152X
#define CONFIG_SCSI_AHA152X_MODULE 1
#undef  CONFIG_SCSI_AHA1542
#define CONFIG_SCSI_AHA1542_MODULE 1
#undef  CONFIG_SCSI_AHA1740
#define CONFIG_SCSI_AHA1740_MODULE 1
#undef  CONFIG_SCSI_AIC7XXX
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#undef  CONFIG_AIC7XXX_TCQ_ON_BY_DEFAULT
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE (8)
#undef  CONFIG_AIC7XXX_PROC_STATS
#define CONFIG_AIC7XXX_RESET_DELAY (5)
#undef  CONFIG_SCSI_ADVANSYS
#define CONFIG_SCSI_ADVANSYS_MODULE 1
#undef  CONFIG_SCSI_IN2000
#define CONFIG_SCSI_IN2000_MODULE 1
#undef  CONFIG_SCSI_AM53C974
#define CONFIG_SCSI_AM53C974_MODULE 1
#undef  CONFIG_SCSI_MEGARAID
#define CONFIG_SCSI_MEGARAID_MODULE 1
#undef  CONFIG_SCSI_BUSLOGIC
#define CONFIG_SCSI_BUSLOGIC_MODULE 1
#undef  CONFIG_SCSI_OMIT_FLASHPOINT
#undef  CONFIG_SCSI_CPQFCTS
#define CONFIG_SCSI_CPQFCTS_MODULE 1
#undef  CONFIG_SCSI_DMX3191D
#define CONFIG_SCSI_DMX3191D_MODULE 1
#undef  CONFIG_SCSI_DTC3280
#define CONFIG_SCSI_DTC3280_MODULE 1
#undef  CONFIG_SCSI_EATA
#define CONFIG_SCSI_EATA_MODULE 1
#undef  CONFIG_SCSI_EATA_TAGGED_QUEUE
#undef  CONFIG_SCSI_EATA_LINKED_COMMANDS
#define CONFIG_SCSI_EATA_MAX_TAGS (16)
#undef  CONFIG_SCSI_EATA_DMA
#define CONFIG_SCSI_EATA_DMA_MODULE 1
#undef  CONFIG_SCSI_EATA_PIO
#define CONFIG_SCSI_EATA_PIO_MODULE 1
#undef  CONFIG_SCSI_FUTURE_DOMAIN
#define CONFIG_SCSI_FUTURE_DOMAIN_MODULE 1
#undef  CONFIG_SCSI_GDTH
#define CONFIG_SCSI_GDTH_MODULE 1
#undef  CONFIG_SCSI_GENERIC_NCR5380
#define CONFIG_SCSI_GENERIC_NCR5380_MODULE 1
#undef  CONFIG_SCSI_GENERIC_NCR53C400
#define CONFIG_SCSI_G_NCR5380_PORT 1
#undef  CONFIG_SCSI_G_NCR5380_MEM
#undef  CONFIG_SCSI_IPS
#define CONFIG_SCSI_IPS_MODULE 1
#undef  CONFIG_SCSI_INITIO
#define CONFIG_SCSI_INITIO_MODULE 1
#undef  CONFIG_SCSI_INIA100
#define CONFIG_SCSI_INIA100_MODULE 1
#undef  CONFIG_SCSI_PPA
#define CONFIG_SCSI_PPA_MODULE 1
#undef  CONFIG_SCSI_IMM
#define CONFIG_SCSI_IMM_MODULE 1
#undef  CONFIG_SCSI_IZIP_EPP16
#undef  CONFIG_SCSI_IZIP_SLOW_CTR
#undef  CONFIG_SCSI_NCR53C406A
#define CONFIG_SCSI_NCR53C406A_MODULE 1
#undef  CONFIG_SCSI_NCR53C7xx
#define CONFIG_SCSI_NCR53C7xx_MODULE 1
#undef  CONFIG_SCSI_NCR53C7xx_sync
#undef  CONFIG_SCSI_NCR53C7xx_FAST
#undef  CONFIG_SCSI_NCR53C7xx_DISCONNECT
#undef  CONFIG_SCSI_NCR53C8XX
#define CONFIG_SCSI_NCR53C8XX_MODULE 1
#define CONFIG_SCSI_SYM53C8XX 1
#define CONFIG_SCSI_NCR53C8XX_DEFAULT_TAGS (4)
#define CONFIG_SCSI_NCR53C8XX_MAX_TAGS (32)
#define CONFIG_SCSI_NCR53C8XX_SYNC (20)
#undef  CONFIG_SCSI_NCR53C8XX_PROFILE
#undef  CONFIG_SCSI_NCR53C8XX_IOMAPPED
#undef  CONFIG_SCSI_NCR53C8XX_PQS_PDS
#undef  CONFIG_SCSI_NCR53C8XX_SYMBIOS_COMPAT
#undef  CONFIG_SCSI_PAS16
#define CONFIG_SCSI_PAS16_MODULE 1
#undef  CONFIG_SCSI_PCI2000
#define CONFIG_SCSI_PCI2000_MODULE 1
#undef  CONFIG_SCSI_PCI2220I
#define CONFIG_SCSI_PCI2220I_MODULE 1
#undef  CONFIG_SCSI_PSI240I
#define CONFIG_SCSI_PSI240I_MODULE 1
#undef  CONFIG_SCSI_QLOGIC_FAS
#define CONFIG_SCSI_QLOGIC_FAS_MODULE 1
#undef  CONFIG_SCSI_QLOGIC_ISP
#define CONFIG_SCSI_QLOGIC_ISP_MODULE 1
#undef  CONFIG_SCSI_QLOGIC_FC
#define CONFIG_SCSI_QLOGIC_FC_MODULE 1
#undef  CONFIG_SCSI_QLOGIC_1280
#define CONFIG_SCSI_QLOGIC_1280_MODULE 1
#undef  CONFIG_SCSI_SEAGATE
#define CONFIG_SCSI_SEAGATE_MODULE 1
#undef  CONFIG_SCSI_SIM710
#define CONFIG_SCSI_SIM710_MODULE 1
#undef  CONFIG_SCSI_SYM53C416
#define CONFIG_SCSI_SYM53C416_MODULE 1
#undef  CONFIG_SCSI_DC390T
#define CONFIG_SCSI_DC390T_MODULE 1
#undef  CONFIG_SCSI_DC390T_NOGENSUPP
#undef  CONFIG_SCSI_T128
#define CONFIG_SCSI_T128_MODULE 1
#undef  CONFIG_SCSI_U14_34F
#define CONFIG_SCSI_U14_34F_MODULE 1
#undef  CONFIG_SCSI_U14_34F_LINKED_COMMANDS
#define CONFIG_SCSI_U14_34F_MAX_TAGS (8)
#undef  CONFIG_SCSI_ULTRASTOR
#define CONFIG_SCSI_ULTRASTOR_MODULE 1
#undef  CONFIG_SCSI_DEBUG
#define CONFIG_SCSI_DEBUG_MODULE 1
/*
 * PCMCIA SCSI adapter support
 */
#undef  CONFIG_SCSI_PCMCIA
/*
 * Fusion MPT device support
 */
#undef  CONFIG_FUSION
#undef  CONFIG_FUSION_BOOT
#undef  CONFIG_FUSION_ISENSE
#undef  CONFIG_FUSION_CTL
#undef  CONFIG_FUSION_LAN
/*
 * IEEE 1394 (FireWire) support
 */
#undef  CONFIG_IEEE1394
/*
 * I2O device support
 */
#undef  CONFIG_I2O
/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#undef  CONFIG_DUMMY
#define CONFIG_DUMMY_MODULE 1
#undef  CONFIG_BONDING
#define CONFIG_BONDING_MODULE 1
#undef  CONFIG_EQUALIZER
#define CONFIG_EQUALIZER_MODULE 1
#undef  CONFIG_TUN
#define CONFIG_TUN_MODULE 1
#undef  CONFIG_ETHERTAP
#define CONFIG_ETHERTAP_MODULE 1
#undef  CONFIG_NET_SB1000
#define CONFIG_NET_SB1000_MODULE 1
/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_NET_VENDOR_3COM 1
#undef  CONFIG_EL1
#define CONFIG_EL1_MODULE 1
#undef  CONFIG_EL2
#define CONFIG_EL2_MODULE 1
#undef  CONFIG_ELPLUS
#define CONFIG_ELPLUS_MODULE 1
#undef  CONFIG_EL16
#define CONFIG_EL16_MODULE 1
#undef  CONFIG_EL3
#define CONFIG_EL3_MODULE 1
#undef  CONFIG_3C515
#define CONFIG_3C515_MODULE 1
#undef  CONFIG_VORTEX
#define CONFIG_VORTEX_MODULE 1
#undef  CONFIG_LANCE
#define CONFIG_LANCE_MODULE 1
#define CONFIG_NET_VENDOR_SMC 1
#undef  CONFIG_WD80x3
#define CONFIG_WD80x3_MODULE 1
#undef  CONFIG_ULTRA
#define CONFIG_ULTRA_MODULE 1
#undef  CONFIG_SMC9194
#define CONFIG_SMC9194_MODULE 1
#define CONFIG_NET_VENDOR_RACAL 1
#undef  CONFIG_NI5010
#define CONFIG_NI5010_MODULE 1
#undef  CONFIG_NI52
#define CONFIG_NI52_MODULE 1
#undef  CONFIG_NI65
#define CONFIG_NI65_MODULE 1
#undef  CONFIG_AT1700
#define CONFIG_AT1700_MODULE 1
#undef  CONFIG_DEPCA
#define CONFIG_DEPCA_MODULE 1
#undef  CONFIG_HP100
#define CONFIG_HP100_MODULE 1
#define CONFIG_NET_ISA 1
#undef  CONFIG_E2100
#define CONFIG_E2100_MODULE 1
#undef  CONFIG_EEXPRESS
#define CONFIG_EEXPRESS_MODULE 1
#undef  CONFIG_EEXPRESS_PRO
#define CONFIG_EEXPRESS_PRO_MODULE 1
#undef  CONFIG_HPLAN_PLUS
#define CONFIG_HPLAN_PLUS_MODULE 1
#undef  CONFIG_HPLAN
#define CONFIG_HPLAN_MODULE 1
#undef  CONFIG_ETH16I
#define CONFIG_ETH16I_MODULE 1
#undef  CONFIG_NE2000
#define CONFIG_NE2000_MODULE 1
#undef  CONFIG_SK_G16
#define CONFIG_SK_G16_MODULE 1
#define CONFIG_NET_PCI 1
#undef  CONFIG_PCNET32
#define CONFIG_PCNET32_MODULE 1
#undef  CONFIG_ADAPTEC_STARFIRE
#define CONFIG_ADAPTEC_STARFIRE_MODULE 1
#undef  CONFIG_AC3200
#define CONFIG_AC3200_MODULE 1
#undef  CONFIG_APRICOT
#define CONFIG_APRICOT_MODULE 1
#undef  CONFIG_CS89x0
#define CONFIG_CS89x0_MODULE 1
#undef  CONFIG_TULIP
#define CONFIG_TULIP_MODULE 1
#undef  CONFIG_DE4X5
#define CONFIG_DE4X5_MODULE 1
#undef  CONFIG_DGRS
#define CONFIG_DGRS_MODULE 1
#undef  CONFIG_DM9102
#define CONFIG_DM9102_MODULE 1
#define CONFIG_EEPRO100 1
#undef  CONFIG_EEPRO100_PM
#undef  CONFIG_NATSEMI
#define CONFIG_NATSEMI_MODULE 1
#undef  CONFIG_NE2K_PCI
#define CONFIG_NE2K_PCI_MODULE 1
#undef  CONFIG_8139TOO
#define CONFIG_8139TOO_MODULE 1
#undef  CONFIG_RTL8129
#define CONFIG_RTL8129_MODULE 1
#undef  CONFIG_SIS900
#define CONFIG_SIS900_MODULE 1
#undef  CONFIG_EPIC100
#define CONFIG_EPIC100_MODULE 1
#undef  CONFIG_SUNDANCE
#define CONFIG_SUNDANCE_MODULE 1
#undef  CONFIG_TLAN
#define CONFIG_TLAN_MODULE 1
#undef  CONFIG_VIA_RHINE
#define CONFIG_VIA_RHINE_MODULE 1
#undef  CONFIG_WINBOND_840
#define CONFIG_WINBOND_840_MODULE 1
#undef  CONFIG_HAPPYMEAL
#define CONFIG_HAPPYMEAL_MODULE 1
#undef  CONFIG_NET_POCKET
/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#define CONFIG_ACENIC_MODULE 1
#undef  CONFIG_ACENIC_OMIT_TIGON_I
#undef  CONFIG_HAMACHI
#define CONFIG_HAMACHI_MODULE 1
#undef  CONFIG_YELLOWFIN
#define CONFIG_YELLOWFIN_MODULE 1
#undef  CONFIG_SK98LIN
#define CONFIG_SK98LIN_MODULE 1
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#define CONFIG_PLIP_MODULE 1
#undef  CONFIG_PPP
#define CONFIG_PPP_MODULE 1
#undef  CONFIG_PPP_MULTILINK
#undef  CONFIG_PPP_ASYNC
#define CONFIG_PPP_ASYNC_MODULE 1
#undef  CONFIG_PPP_SYNC_TTY
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#undef  CONFIG_PPP_DEFLATE
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef  CONFIG_PPP_BSDCOMP
#define CONFIG_PPP_BSDCOMP_MODULE 1
#undef  CONFIG_PPPOE
#define CONFIG_PPPOE_MODULE 1
#undef  CONFIG_SLIP
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#define CONFIG_SLIP_MODE_SLIP6 1
/*
 * Wireless LAN (non-hamradio)
 */
#undef  CONFIG_NET_RADIO
/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER
/*
 * Wan interfaces
 */
#undef  CONFIG_WAN
/*
 * PCMCIA network device support
 */
#undef  CONFIG_NET_PCMCIA
/*
 * Amateur Radio support
 */
#undef  CONFIG_HAMRADIO
/*
 * IrDA (infrared) support
 */
#undef  CONFIG_IRDA
/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN
/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef  CONFIG_CD_NO_IDESCSI
/*
 * Input core support
 */
#undef  CONFIG_INPUT
#define CONFIG_INPUT_MODULE 1
#undef  CONFIG_INPUT_KEYBDEV
#define CONFIG_INPUT_KEYBDEV_MODULE 1
#undef  CONFIG_INPUT_MOUSEDEV
#define CONFIG_INPUT_MOUSEDEV_MODULE 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X (1024)
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y (768)
#undef  CONFIG_INPUT_JOYDEV
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef  CONFIG_INPUT_EVDEV
#define CONFIG_INPUT_EVDEV_MODULE 1
/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_SERIAL 1
#undef  CONFIG_SERIAL_CONSOLE
#undef  CONFIG_SERIAL_EXTENDED
#undef  CONFIG_SERIAL_NONSTANDARD
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT (256)
#undef  CONFIG_PRINTER
#define CONFIG_PRINTER_MODULE 1
#define CONFIG_LP_CONSOLE 1
#undef  CONFIG_PPDEV
#define CONFIG_PPDEV_MODULE 1
/*
 * I2C support
 */
#undef  CONFIG_I2C
#define CONFIG_I2C_MODULE 1
#undef  CONFIG_I2C_ALGOBIT
#define CONFIG_I2C_ALGOBIT_MODULE 1
#undef  CONFIG_I2C_PHILIPSPAR
#define CONFIG_I2C_PHILIPSPAR_MODULE 1
#undef  CONFIG_I2C_ELV
#define CONFIG_I2C_ELV_MODULE 1
#undef  CONFIG_I2C_VELLEMAN
#define CONFIG_I2C_VELLEMAN_MODULE 1
#undef  CONFIG_I2C_ALGOPCF
#define CONFIG_I2C_ALGOPCF_MODULE 1
#undef  CONFIG_I2C_ELEKTOR
#define CONFIG_I2C_ELEKTOR_MODULE 1
#undef  CONFIG_I2C_CHARDEV
#define CONFIG_I2C_CHARDEV_MODULE 1
/*
 * Mice
 */
#undef  CONFIG_BUSMOUSE
#define CONFIG_BUSMOUSE_MODULE 1
#undef  CONFIG_ATIXL_BUSMOUSE
#define CONFIG_ATIXL_BUSMOUSE_MODULE 1
#undef  CONFIG_LOGIBUSMOUSE
#define CONFIG_LOGIBUSMOUSE_MODULE 1
#undef  CONFIG_MS_BUSMOUSE
#define CONFIG_MS_BUSMOUSE_MODULE 1
#undef  CONFIG_MOUSE
#define CONFIG_MOUSE_MODULE 1
#define CONFIG_PSMOUSE 1
#undef  CONFIG_82C710_MOUSE
#define CONFIG_82C710_MOUSE_MODULE 1
#undef  CONFIG_PC110_PAD
#define CONFIG_PC110_PAD_MODULE 1
/*
 * Joysticks
 */
#undef  CONFIG_JOYSTICK
/*
 * Input core support is needed for joysticks
 */
#undef  CONFIG_QIC02_TAPE
/*
 * Watchdog Cards
 */
#undef  CONFIG_WATCHDOG
#undef  CONFIG_INTEL_RNG
#define CONFIG_NVRAM 1
#undef  CONFIG_RTC
#define CONFIG_RTC_MODULE 1
#undef  CONFIG_DTLK
#undef  CONFIG_R3964
#undef  CONFIG_APPLICOM
/*
 * Ftape, the floppy tape device driver
 */
#undef  CONFIG_FTAPE
#undef  CONFIG_AGP
#define CONFIG_AGP_MODULE 1
#define CONFIG_AGP_INTEL 1
#define CONFIG_AGP_I810 1
#define CONFIG_AGP_VIA 1
#define CONFIG_AGP_AMD 1
#define CONFIG_AGP_SIS 1
#define CONFIG_AGP_ALI 1
#define CONFIG_DRM 1
#undef  CONFIG_DRM_TDFX
#define CONFIG_DRM_TDFX_MODULE 1
#undef  CONFIG_DRM_GAMMA
#define CONFIG_DRM_GAMMA_MODULE 1
#undef  CONFIG_DRM_R128
#define CONFIG_DRM_R128_MODULE 1
#undef  CONFIG_DRM_I810
#define CONFIG_DRM_I810_MODULE 1
#undef  CONFIG_DRM_MGA
#define CONFIG_DRM_MGA_MODULE 1
#define CONFIG_PCMCIA_SERIAL 1
/*
 * PCMCIA character device support
 */
#undef  CONFIG_PCMCIA_SERIAL_CS
#undef  CONFIG_PCMCIA_SERIAL_CB
/*
 * Multimedia devices
 */
#undef  CONFIG_VIDEO_DEV
#define CONFIG_VIDEO_DEV_MODULE 1
/*
 * Video For Linux
 */
#define CONFIG_VIDEO_PROC_FS 1
#undef  CONFIG_I2C_PARPORT
#define CONFIG_I2C_PARPORT_MODULE 1
/*
 * Video Adapters
 */
#undef  CONFIG_VIDEO_BT848
#define CONFIG_VIDEO_BT848_MODULE 1
#undef  CONFIG_VIDEO_PMS
#define CONFIG_VIDEO_PMS_MODULE 1
#undef  CONFIG_VIDEO_BWQCAM
#define CONFIG_VIDEO_BWQCAM_MODULE 1
#undef  CONFIG_VIDEO_CQCAM
#define CONFIG_VIDEO_CQCAM_MODULE 1
#undef  CONFIG_VIDEO_CPIA
#define CONFIG_VIDEO_CPIA_MODULE 1
#undef  CONFIG_VIDEO_CPIA_PP
#define CONFIG_VIDEO_CPIA_PP_MODULE 1
#undef  CONFIG_VIDEO_CPIA_USB
#define CONFIG_VIDEO_CPIA_USB_MODULE 1
#undef  CONFIG_VIDEO_SAA5249
#define CONFIG_VIDEO_SAA5249_MODULE 1
#undef  CONFIG_TUNER_3036
#define CONFIG_TUNER_3036_MODULE 1
#undef  CONFIG_VIDEO_STRADIS
#define CONFIG_VIDEO_STRADIS_MODULE 1
#undef  CONFIG_VIDEO_ZORAN
#define CONFIG_VIDEO_ZORAN_MODULE 1
#undef  CONFIG_VIDEO_BUZ
#define CONFIG_VIDEO_BUZ_MODULE 1
#undef  CONFIG_VIDEO_ZR36120
#define CONFIG_VIDEO_ZR36120_MODULE 1
/*
 * Radio Adapters
 */
#undef  CONFIG_RADIO_CADET
#undef  CONFIG_RADIO_RTRACK
#undef  CONFIG_RADIO_RTRACK2
#undef  CONFIG_RADIO_AZTECH
#undef  CONFIG_RADIO_GEMTEK
#undef  CONFIG_RADIO_MAESTRO
#undef  CONFIG_RADIO_MIROPCM20
#undef  CONFIG_RADIO_SF16FMI
#undef  CONFIG_RADIO_TERRATEC
#undef  CONFIG_RADIO_TRUST
#undef  CONFIG_RADIO_TYPHOON
#undef  CONFIG_RADIO_ZOLTRIX
/*
 * File systems
 */
#undef  CONFIG_QUOTA
#undef  CONFIG_AUTOFS_FS
#define CONFIG_AUTOFS_FS_MODULE 1
#define CONFIG_AUTOFS4_FS 1
#define CONFIG_REISERFS_FS 1
#undef  CONFIG_REISERFS_CHECK
#undef  CONFIG_ADFS_FS
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#define CONFIG_HFS_FS_MODULE 1
#undef  CONFIG_BFS_FS
#undef  CONFIG_FAT_FS
#define CONFIG_FAT_FS_MODULE 1
#undef  CONFIG_MSDOS_FS
#define CONFIG_MSDOS_FS_MODULE 1
#undef  CONFIG_UMSDOS_FS
#define CONFIG_UMSDOS_FS_MODULE 1
#undef  CONFIG_VFAT_FS
#define CONFIG_VFAT_FS_MODULE 1
#undef  CONFIG_EFS_FS
#undef  CONFIG_CRAMFS
#undef  CONFIG_RAMFS
#define CONFIG_ISO9660_FS 1
#define CONFIG_JOLIET 1
#define CONFIG_MINIX_FS 1
#undef  CONFIG_NTFS_FS
#define CONFIG_NTFS_FS_MODULE 1
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_HPFS_FS_MODULE 1
#define CONFIG_PROC_FS 1
#define CONFIG_DEVFS_FS 1
#undef  CONFIG_DEVFS_MOUNT
#undef  CONFIG_DEVFS_DEBUG
#define CONFIG_DEVPTS_FS 1
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_ROMFS_FS
#define CONFIG_EXT2_FS 1
#undef  CONFIG_SYSV_FS
#undef  CONFIG_UDF_FS
#undef  CONFIG_UFS_FS
/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#define CONFIG_CODA_FS_MODULE 1
#define CONFIG_NFS_FS 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFSD 1
#define CONFIG_NFSD_V3 1
#define CONFIG_SUNRPC 1
#define CONFIG_LOCKD 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_SMB_FS 1
#define CONFIG_SMB_NLS_DEFAULT 1
#define CONFIG_SMB_NLS_REMOTE "cp437"
#undef  CONFIG_NCP_FS
/*
 * Partition Types
 */
#undef  CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_SMB_NLS 1
#define CONFIG_NLS 1
/*
 * Native Language Support
 */
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef  CONFIG_NLS_CODEPAGE_437
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_737
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_775
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_850
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_852
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_855
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_857
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_860
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_861
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_862
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_863
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_864
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_865
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_866
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_869
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_874
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_932
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_936
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_949
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#undef  CONFIG_NLS_CODEPAGE_950
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#undef  CONFIG_NLS_ISO8859_1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#undef  CONFIG_NLS_ISO8859_2
#define CONFIG_NLS_ISO8859_2_MODULE 1
#undef  CONFIG_NLS_ISO8859_3
#define CONFIG_NLS_ISO8859_3_MODULE 1
#undef  CONFIG_NLS_ISO8859_4
#define CONFIG_NLS_ISO8859_4_MODULE 1
#undef  CONFIG_NLS_ISO8859_5
#define CONFIG_NLS_ISO8859_5_MODULE 1
#undef  CONFIG_NLS_ISO8859_6
#define CONFIG_NLS_ISO8859_6_MODULE 1
#undef  CONFIG_NLS_ISO8859_7
#define CONFIG_NLS_ISO8859_7_MODULE 1
#undef  CONFIG_NLS_ISO8859_8
#define CONFIG_NLS_ISO8859_8_MODULE 1
#undef  CONFIG_NLS_ISO8859_9
#define CONFIG_NLS_ISO8859_9_MODULE 1
#undef  CONFIG_NLS_ISO8859_14
#define CONFIG_NLS_ISO8859_14_MODULE 1
#undef  CONFIG_NLS_ISO8859_15
#define CONFIG_NLS_ISO8859_15_MODULE 1
#undef  CONFIG_NLS_KOI8_R
#define CONFIG_NLS_KOI8_R_MODULE 1
#undef  CONFIG_NLS_UTF8
#define CONFIG_NLS_UTF8_MODULE 1
/*
 * Console drivers
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_VIDEO_SELECT 1
#undef  CONFIG_MDA_CONSOLE
/*
 * Frame-buffer support
 */
#define CONFIG_FB 1
#define CONFIG_DUMMY_CONSOLE 1
#undef  CONFIG_FB_RIVA
#undef  CONFIG_FB_CLGEN
#undef  CONFIG_FB_PM2
#undef  CONFIG_FB_CYBER2000
#define CONFIG_FB_VESA 1
#undef  CONFIG_FB_VGA16
#undef  CONFIG_FB_HGA
#define CONFIG_VIDEO_SELECT 1
#undef  CONFIG_FB_MATROX
#undef  CONFIG_FB_ATY
#undef  CONFIG_FB_ATY128
#undef  CONFIG_FB_3DFX
#undef  CONFIG_FB_SIS
#undef  CONFIG_FB_VIRTUAL
#undef  CONFIG_FBCON_ADVANCED
#define CONFIG_FBCON_CFB8 1
#define CONFIG_FBCON_CFB16 1
#define CONFIG_FBCON_CFB24 1
#define CONFIG_FBCON_CFB32 1
#undef  CONFIG_FBCON_FONTWIDTH8_ONLY
#undef  CONFIG_FBCON_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1
/*
 * Sound
 */
#define CONFIG_SOUND 1
#undef  CONFIG_SOUND_CMPCI
#undef  CONFIG_SOUND_EMU10K1
#undef  CONFIG_SOUND_FUSION
#undef  CONFIG_SOUND_CS4281
#undef  CONFIG_SOUND_ES1370
#undef  CONFIG_SOUND_ES1371
#undef  CONFIG_SOUND_ESSSOLO1
#undef  CONFIG_SOUND_MAESTRO
#undef  CONFIG_SOUND_SONICVIBES
#undef  CONFIG_SOUND_TRIDENT
#undef  CONFIG_SOUND_MSNDCLAS
#undef  CONFIG_SOUND_MSNDPIN
#undef  CONFIG_SOUND_VIA82CXXX
#undef  CONFIG_SOUND_YMFPCI
#define CONFIG_SOUND_OSS 1
#undef  CONFIG_SOUND_TRACEINIT
#undef  CONFIG_SOUND_DMAP
#undef  CONFIG_SOUND_AD1816
#undef  CONFIG_SOUND_SGALAXY
#undef  CONFIG_SOUND_ADLIB
#undef  CONFIG_SOUND_ACI_MIXER
#undef  CONFIG_SOUND_CS4232
#undef  CONFIG_SOUND_SSCAPE
#undef  CONFIG_SOUND_GUS
#undef  CONFIG_SOUND_ICH
#undef  CONFIG_SOUND_VMIDI
#undef  CONFIG_SOUND_TRIX
#undef  CONFIG_SOUND_MSS
#undef  CONFIG_SOUND_MPU401
#undef  CONFIG_SOUND_NM256
#undef  CONFIG_SOUND_MAD16
#undef  CONFIG_SOUND_PAS
#undef  CONFIG_SOUND_PSS
#undef  CONFIG_SOUND_SB
#undef  CONFIG_SOUND_AWE32_SYNTH
#undef  CONFIG_SOUND_WAVEFRONT
#undef  CONFIG_SOUND_MAUI
#undef  CONFIG_SOUND_YM3812
#undef  CONFIG_SOUND_OPL3SA1
#undef  CONFIG_SOUND_OPL3SA2
#undef  CONFIG_SOUND_YMPCI
#undef  CONFIG_SOUND_YMFPCI
#undef  CONFIG_SOUND_UART6850
#undef  CONFIG_SOUND_AEDSP16
#undef  CONFIG_SOUND_TVMIXER
#define CONFIG_SOUND_TVMIXER_MODULE 1
/*
 * USB support
 */
#define CONFIG_USB 1
#undef  CONFIG_USB_DEBUG
/*
 * Miscellaneous USB options
 */
#undef  CONFIG_USB_DEVICEFS
#undef  CONFIG_USB_BANDWIDTH
/*
 * USB Controllers
 */
#define CONFIG_USB_UHCI_ALT 1
#undef  CONFIG_USB_OHCI
/*
 * USB Device Class drivers
 */
#undef  CONFIG_USB_AUDIO
#undef  CONFIG_USB_BLUETOOTH
#define CONFIG_USB_STORAGE 1
#undef  CONFIG_USB_STORAGE_DEBUG
#undef  CONFIG_USB_STORAGE_FREECOM
#undef  CONFIG_USB_ACM
#undef  CONFIG_USB_PRINTER
/*
 * USB Human Interface Devices (HID)
 */
#undef  CONFIG_USB_HID
#undef  CONFIG_USB_KBD
#undef  CONFIG_USB_MOUSE
#undef  CONFIG_USB_WACOM
/*
 * USB Imaging devices
 */
#undef  CONFIG_USB_DC2XX
#undef  CONFIG_USB_MDC800
#undef  CONFIG_USB_SCANNER
#undef  CONFIG_USB_MICROTEK
/*
 * USB Multimedia devices
 */
#undef  CONFIG_USB_IBMCAM
#undef  CONFIG_USB_OV511
#undef  CONFIG_USB_DSBR
#undef  CONFIG_USB_DABUSB
/*
 * USB Network adaptors
 */
#undef  CONFIG_USB_PLUSB
#undef  CONFIG_USB_PEGASUS
#undef  CONFIG_USB_NET1080
/*
 * USB port drivers
 */
#undef  CONFIG_USB_USS720
/*
 * USB Serial Converter support
 */
#undef  CONFIG_USB_SERIAL
/*
 * USB misc drivers
 */
#undef  CONFIG_USB_RIO500
/*
 * Kernel hacking
 */
#undef  CONFIG_MAGIC_SYSRQ
