# Copyright 1999-2000 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# Author Grant Goodyear <g2boojum@gentoo.org>
# $Header: /var/cvsroot/gentoo-x86/sys-apps/lsof/lsof-4.56.ebuild,v 1.2 2001/06/29 05:46:23 drobbins Exp $

#Not a good idea to override ${P}; changed to ${P2}
P0=lsof_4.56
#${A} autogenerated from SRC_URI, no need to define here
S0=${WORKDIR}
S=${WORKDIR}/${P0}
DESCRIPTION="Lists open files for running Unix processes"
SRC_URI="ftp://vic.cc.purdue.edu/pub/tools/unix/lsof/lsof_4.56_W.tar.gz ftp://ftp.cerias.purdue.edu/pub/tools/unix/sysutils/lsof/lsof_4.56_W.tar.gz"
HOMEPAGE="http://"

DEPEND="virtual/glibc virtual/kernel"

#This pkg appears to be highly kernel-dependent.

src_unpack() {
    unpack ${A}
    cd ${S0}
    try tar xvf ${P0}.tar
}

src_compile() {
    #interactive script: Enable HASSECURITY, WARNINGSTATE, and HASKERNIDCK
    #is there a way to avoid the "echo to a file + file read"?
    #Just piping in the results didn't seem to work.
    echo -e "y\ny\ny\nn\ny\ny\n" > junk
    #${T} is for temporary stuff.  Don't create stray files just anywhere
	./Configure linux < junk
	#simple Makefile hack to insert CFLAGS
    cp Makefile Makefile.orig
	sed -e "s/-DLINUXV/${CFLAGS} -DLINUXV/" Makefile.orig > Makefile
	try make all
}

src_install () {
    doman lsof.8
    #/usr/sbin is a good location -- drobbins
	dosbin lsof
    # .a libs not needed during boot so they go in /usr/lib -- drobbins
    dolib lib/liblsof.a
    dodoc 
    insinto /usr/share/lsof/scripts
    doins scripts/*
}

