#!/sbin/runscript

depend() {
	need net
	use jabber-server
}

start() {
	ebegin "Starting AIM Jabber Transport"
	jabberd -B -c /etc/jabber/aimtrans.xml -H /var/spool/jabber >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Stoping AIM Jabber Transport"
	kill `cat /var/log/jabber/aim.pid`
	sleep 2
	if ( -f /var/log/jabber/aim.pid ); then
		kill -9 `cat /var/log/jabber/aim.pid`
		rm -f /var/log/jabber/aim.pid
	fi
	eend $?
}
