#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

PKCSSLOTDPID="/var/run/pkcsslotd.pid"

depend() {
	need tcsd
}

start() {
	ebegin "Starting ${SVCNAME}"

	# detect available tokens and 
	# set up /var/lib/opencryptoki/pk_config_data
	/usr/sbin/pkcs11_startup

	start-stop-daemon --start --exec /usr/sbin/pkcsslotd --pidfile "${PKCSSLOTDPID}"
	eend $? "Check your logs to see why startup failed"
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec /usr/sbin/pkcsslotd --pidfile "${PKCSSLOTDPID}"
	eend $?
}

