# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/keyring/keyring-1.0.ebuild,v 1.1 2012/12/19 20:47:59 prometheanfire Exp $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=4

inherit distutils

MY_PN=${PN#python-}
S="${WORKDIR}/${MY_PN}-${PV}"
DESCRIPTION="Provides a easy way to access the system keyring service from
python."
HOMEPAGE="http://pypi.python.org/pypi/keyring"
SRC_URI="mirror://pypi/k/${MY_PN}/${MY_PN}-${PV}.zip"
LICENSE="BSD-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=""

src_install() {
	distutils_src_install
}
