# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/keyring/keyring-1.0.ebuild,v 1.2 2012/12/28 05:34:57 prometheanfire Exp $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=4

inherit distutils eutils

MY_PN=${PN#python-}
S="${WORKDIR}/${MY_PN}-${PV}"
DESCRIPTION="Provides a easy way to access the system keyring service from
python."
HOMEPAGE="https://bitbucket.org/kang/python-keyring-lib"
SRC_URI="mirror://pypi/k/${MY_PN}/${MY_PN}-${PV}.zip"
LICENSE="PSF-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE="test"
DEPEND="dev-python/setuptools
		test? ( dev-python/pytest
				dev-python/pytest-runner
				dev-python/unittest2 )"
RDEPEND=""

src_prepare() {
	epatch "${FILESDIR}/setup-1.0.patch"
}

src_test() {
	PYTHONPATH="build/lib" "$(PYTHON)" keyring/tests/test_util.py
	PYTHONPATH="build/lib" "$(PYTHON)" keyring/tests/test_backend.py
	PYTHONPATH="build/lib" "$(PYTHON)" keyring/tests/test_core.py
	PYTHONPATH="build/lib" "$(PYTHON)" keyring/tests/test_cli.py
}

src_install() {
	distutils_src_install
}
