# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-java/errorlist/errorlist-1.3.2.ebuild,v 1.2 2004/10/20 05:34:17 absinthe Exp $

inherit java-pkg

DESCRIPTION="jedit plugin: The ErrorList plugin provides one-click access, and on-the-spot highlighting of errors generated by EditBus-aware packages, such as the Console."

HOMEPAGE="http://plugins.jedit.org/plugins/?ErrorList"
SRC_URI="mirror://sourceforge/jedit-plugins/ErrorList-${PV}.tgz"
LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE=""
DEPEND=">=app-editors/jedit-4.2
	dev-java/ant"
#RDEPEND=""

S=${WORKDIR}/ErrorList

src_unpack() {
	unpack ${A}
	rm -f ErrorList.jar
}

src_compile() {
	ant dist -Djedit.install.dir=/usr/share/jedit || die "compile failed"
}

src_install() {
	java-pkg_dojar ${WORKDIR}/ErrorList.jar
	dodir /usr/share/jedit/jars
	dosym /usr/share/${PN}/lib/ErrorList.jar /usr/share/jedit/jars/ErrorList.jar
}
