# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# Maintainer: Ben Lutgens,,, <lamer@gentoo.org>
# $Header: /var/cvsroot/gentoo-x86/dev-libs/KXL/KXL-1.1.5.ebuild,v 1.1 2002/07/06 20:32:04 lamer Exp $

# This ebuild was generated by Ebuilder v0.4.

S="${WORKDIR}/${P}"
DESCRIPTION="Development Library for making games and stuff, I think"
SRC_URI="http://kxl.hn.org/download/${P}.tar.gz"
HOMEPAGE="http://kxl.hn.org/"
LICENSE="as-is"
DEPEND=""

src_compile() {
	./configure \
		--host=${CHOST} \
		--prefix=/usr \
		--infodir=/usr/share/info \
		--mandir=/usr/share/man || die "./configure failed"
	# emake (previously known as pmake) is a script that calls the
	# standard GNU make with parallel building options for speedier
	# builds (especially on SMP systems). Try emake first. It might
	# not work for some packages, in which case you'll have to resort
	# to normal "make".
	emake || die
	#make || die
}

src_install () {
	make DESTDIR=${D} install || die
	# If the above installs anything outside of DESTDIR, try the following.
	#make \
	#	prefix=${D}/usr \
	#	mandir=${D}/usr/share/man \
	#	infodir=${D}/usr/share/info \
	#	install || die

	# Install documentation.
	dodoc ChangeLog COPYING README
}
