#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/git/files/git-daemon.initd,v 1.1 2005/10/05 15:05:04 ferdy Exp $

depend() {
	need net
	use logger
}

start() {
	ebegin "Starting git-daemon"
		start-stop-daemon --start --quiet --background \
		--exec /usr/bin/git-daemon -- ${GITDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stoping git-daemon"
		start-stop-daemon --stop --quiet --name git-daemon
	eend $?
}
