#!/sbin/runscript

depend() {
	need net
	need jabber-server
}

start() {
	ebegin "Starting MSN Jabber Transport"
	cd /var/run/jabber
	start-stop-daemon --start --quiet --background --chuid jabber:jabber \
		--exec /usr/lib/PATH/site-packages/PyMSNt -- /etc/jabber/pymsn-t.xml
	eend $?
}

stop() {
	ebegin "Stopping MSN Jabber Transport"
	start-stop-daemon --stop --quiet --pidfile /var/run/jabber/pymsn-t.pid
	eend $?
}
