# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-wireless/rt2x00/rt2x00-9999.ebuild,v 1.8 2006/08/01 12:56:21 uberlord Exp $

inherit linux-mod cvs

DESCRIPTION="Driver for the RaLink RT2x00 wireless chipsets"
HOMEPAGE="http://rt2x00.serialmonkey.com"
LICENSE="GPL-2"

ECVS_SERVER="rt2400.cvs.sourceforge.net:/cvsroot/rt2400"
ECVS_MODULE="source/rt2x00"
ECVS_LOCALNAME="${P}"

KEYWORDS="-* ~amd64 ~x86"
RDEPEND="net-wireless/wireless-tools"

MODULES="D80211 RFKILL RT2400PCI RT2500PCI RT2500USB RT61PCI RT73USB"
MODULES_USE="rfkill rt2400 rt2500 rt61 rt73"
IUSE="asm debug ${MODULES_USE}"

pkg_setup() {
	CONFIG_CHECK="NET_RADIO"
	ERROR_NET_RADIO="${P} requires support for Wireless LAN drivers (non-hamradio) & Wireless Extensions (CONFIG_NET_RADIO)."

	# dScape requires AES
	CONFIG_CHECK="${CONFIG_CHECK} CRYPTO_AES CRYPTO_MICHAEL_MIC"
	ERROR_CRYPTO_AES="${P} requires support for AES Cryptography (CONFIG_CRYPTO_AES)."
	ERROR_CRYPTO_MICHAEL_MIC="${P} requires support for Michael MIC Cryptography (CONFIG_CRYPTO_MICHAEL_MIC)."

	if use rfkill ; then
		CONFIG_CHECK="${CONFIG_CHECK} INPUT"
	fi

	if use rt2400 || use rt2500 || use rt61 ; then
		CONFIG_CHECK="${CONFIG_CHECK} PCI"
	fi

	if use rt2500 || use rt73 ; then
		CONFIG_CHECK="${CONFIG_CHECK} USB"
	fi

	if use rt61 || use rt73 ; then
		CONFIG_CHECK="${CONFIG_CHECK} FW_LOADER"
		ERROR_FW_LOADER="${P} requires support for Firmware module loading (CONFIG_FW_LOADER)."
	fi

	kernel_is lt 2 6 17 && die "${P} requires at least kernel 2.6.17"
	linux-mod_pkg_setup
	BUILD_PARAMS="KERNDIR=${KV_DIR} KERNOUT=${KV_OUT_DIR}"
	BUILD_TARGETS=" " # Target "module" is not supported, so we blank it
}

src_compile() {
	local m= asm="n" button="n" debug="n" full="y" yn= M=

	for m in ${MODULES_USE} ; do
		if use "${m}" ; then
			full="n"
			break
		fi
	done

	if [[ ${full} == "n" ]] ; then
		use asm && asm="y"
		use debug && debug="y"
		use rfkill && button="y"
	else
		ewarn "No module specified in USE flags - building everything."
		button="y"
	fi

	MODULE_NAMES="80211(rt2x00:) rate_control(rt2x00:)"

	# Generate the config file now
	echo "# Config file generated by portage" > config

	for M in ${MODULES} ; do
		local yn="n" m=$(echo "${M}" | tr '[:upper:]' '[:lower:]')
		local um="${m//pci/}"
		um="${um//usb/}"

		if [[ ${M} == "D80211" || ${full} == "y" ]] || use "${um}" ; then
			yn="y"
		fi
		echo "CONFIG_${M}=${yn}" >> config
		echo "CONFIG_${M}_ASM=${asm}" >> config
		echo "CONFIG_${M}_DEBUG=${debug}" >> config
		echo "CONFIG_${M}_BUTTON=${button}" >> config

		if [[ ${M} != "D80211" && ${yn} == "y" ]] ; then
			MODULE_NAMES="${MODULE_NAMES} ${m}(rt2x00:)"
		fi
	done

	# RT61 and RT73 require CONFIG_CRC_ITU_T
	if use rt61 || use rt73 ; then
		echo "CONFIG_CRC_ITU_T=y" >> config
	fi

	linux-mod_src_compile
}

src_install() {
	linux-mod_src_install
	dodoc CHANGELOG COPYING README THANKS
}

pkg_postinst() {
	linux-mod_pkg_postinst

	ewarn
	ewarn "This is a CVS ebuild - please report any bugs to the rt2x00 forums"
	ewarn "http://rt2x00.serialmonkey.com/phpBB2/viewforum.php?f=5"
	ewarn
	ewarn "Any bugs reported to Gentoo will be marked INVALID"
	ewarn
}
