.TH etc-update "1" "March 2002" "gentoolkit 0.1.4" 
.SH NAME
etc-update \- manual page for the etc-update program, a program that traverses
your /etc directory, looking for suitable config file updates
.SH SYNOPSIS
.B etc-update
.SH DESCRIPTION
.I etc-update
is supposed to be run after merging a new package, to see if
there are updates to the configuration files in /etc. 
If a new configuration file will override an old one, 
.I etc-update 
will prompt the user for a decision.
.PP
.I etc-update
will check all directories in \fI/etc/make.global\fR's \fICONFIG_PROTECT\fR variable.
.SH OPTIONS 
.TP
None.
.SH AUTHORS
Jochem Kossen and Leo Lipelis, 2002: etc-update
.br
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002: man page, fixes
.SH "SEE ALSO"
ebuild(5) 
.TP
The \fI/usr/sbin/lintool\fR script. 
