# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="4"

MODULE_AUTHOR="MWX"

inherit perl-module

DESCRIPTION="Perl extension for simple genrating of unique id's"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

RDEPEND="dev-lang/perl
	virtual/perl-Math-BigInt
	virtual/perl-Time-HiRes"
DEPEND="${RDEPEND}"

SRC_TEST="do"
