#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-i18n/skkserv/files/skkserv.initd,v 1.1 2003/08/01 16:32:40 usata Exp $

start() {
	ebegin "Starting skkserv"
	start-stop-daemon --start --quiet --exec /usr/sbin/skkserv
	eend $?
}

stop() {
	ebegin "Stopping skkserv"
	start-stop-daemon --stop --quiet --exec /usr/sbin/skkserv
	eend $?
}
