#!/bin/sh
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/sys-apps/ifplugd/files/ifplugd.action,v 1.2 2003/03/21 15:58:05 wmertens Exp $
#
# Gentoo-specific ifplugd.action
#
# This file gets called by ifplugd when it wants to bring an interface
# up or down.
#

case "$2" in
	up)
		state=start
		;;
	down)
		state=stop
		;;
	*)
		echo "$0: wrong arguments"
		echo "Call with <interface> <up|down>"
		exit 1
		;;
esac

[ -x /etc/init.d/net.$1 ] && /etc/init.d/net.$1 --quiet $state

exit 0
