# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/pcap/pcap-0.4.5.2-r1.ebuild,v 1.2 2012/12/31 14:20:25 ago Exp $

EAPI=5

# ebuild generated by hackport 0.3.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A system-independent interface for user-level packet capture"
HOMEPAGE="https://github.com/bos/pcap"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~ppc ~x86"
IUSE=""

RDEPEND="dev-haskell/network:=[profile?]
		>=dev-lang/ghc-6.12.1:=
		net-libs/libpcap"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
