#!/sbin/runscript

depend() {
	need net
	use jabber-server
}

start() {
	ebegin "Starting MUC Jabber Transport"
	jabberd -B -c /etc/jabber/muctrans.xml -H /var/spool/jabber >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Stoping MUC Jabber Transport"
	kill `cat /var/log/jabber/muctrans.pid`
	sleep 2
	if ( -f /var/log/jabber/muctrans.pid ); then
		kill -9 `cat /var/log/jabber/muctrans.pid`
		rm -f /var/log/jabber/muctrans.pid
	fi
	eend $?
}
