#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/kde-misc/kload/files/kloadd.initd,v 1.1 2005/08/22 21:33:35 sbriesen Exp $

start() {
	ebegin "Starting kloadd"
	start-stop-daemon --start --quiet --exec /usr/sbin/kloadd -- ${PORT} ${BIND} >/dev/null
	eend $?
}

stop() {
	ebegin "Stopping kloadd"
	start-stop-daemon --stop --quiet --exec /usr/sbin/kloadd --retry 10
	eend $?
}
