#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/sys-apps/busybox/files/syslogd.initd,v 1.1 2012/12/04 12:10:35 blueness Exp $

# Note: the syslogd pid file is hard coded
command="/bin/busybox syslogd"
command_args="${SYSLOGD_OPTS}"
pidfile="/var/run/syslogd.pid"

depend() {
	need clock hostname
	provide logger
}
