.TH "idesk" "1" "" "" ""
.SH "NAME"
idesk \- Adds desktop icons to the root X window
.SH "SYNOPSIS"
Idesk allows desktop icons to be added to the root window of an X session, placed freely wherever desired.  The icons "glow" on mouse\-over, and the icons themselves can be any size.  Other attributes, such as font, font size, transparency, and shadows are configurable.
.SH "INSTALLING"
Idesk is known to run on FreeBSD, Linux, NetBSD, OpenBSD.  If a package is not available for your platform, you can compile it from source.
.PP
\fBSteps:\fR
.IP
1. Unpack the source tar.gz to a desired location.\bR
.br
2. From that location, run \fImake\fR.
.br
3. As root from that location, run \fImake install\fR.

.SH "CONFIGURING"
\fBSTEPS\fR
.PP
\fB1.\fR Following the syntax described in \fIideskrc(5)\fR, create a file
in your home directory named .ideskrc.
.PP
\fB2.\fR Create a directory called .idesktop/ in your home directory. 
.PP
\fB3.\fR Inside the new directory, create an icon file with the extension 'lnk'
(e.g., home.lnk).  Inside the file put something like this:
.IP
table Icon
  Caption: Mozilla
  Command: /usr/bin/mozilla 
  Icon: /usr/share/icons/mozilla.png
.br
end
.PP
\fB4.\fR Start idesk as described in \fIRUNNING\fR below, or kill and
restart idesk if it's already running.
.PP
\fB5.\fR Move your new icon to where you would like it to be, and verify
it works correctly.
.PP
\fB6.\fR Repeat steps 3-5 for any additional icons you would like to have.
.PP
\fB7.\fR After you have your icons finished and where you want them, change
\fILocked\fR from 'false' to 'true' in .ideskrc.
.PP
\fB8.\fR (optional) Add 'idesk' to your .xinitrc or other startup scripts to run it automatically.

.SH "RUNNING"
Idesk runs as a background process.  One suggested way to start idesk is:
.IP
nohup idesk > /dev/null &
.PP
After Idesk is running, click on an icon to start whatever command you 
assigned it.  Currently 'kill -HUP' will terminate the program.  It is 
required to restart idesk when you add new icons (.lnk files), unless
you are running some other utility that runs on top of idesk, such as
Fluxspace.

You can reload existing .lnk files in ~/.idesktop/ by middle-clicking 
on any icon.

.SH "SEE ALSO"
\fIideskrc(5)\fR

.SH "PROGRAM AUTHORS"
.IP
Chris Roberts (nikon) <nikon@sc.rr.com>
.br
Bryn (curious) <curious@ihug.com.au>
.br
Christopher Morris <cmorri9@lsu.edu>
.br
Tim Finley <timmfin@timmfin.net>
.SH "MANPAGE AUTHOR"
.IP
Dylan Carlson <absinthe@gentoo.org>
