.TH "idesk" "1" "" "" ""
.SH "NAME"
Idesk \-\-  program that draws desktop icons.
.SH "SYNOPSIS"
Idesk is program that draws desktop icons. Each icon will execute a shell command when double\-clicked (set to single\-click by an option). The icons can be moved on the desktop by dragging them, and the icons will remember their positions on start\-up. Oh yea, forgot there is cool eye\-candy.
                                                                                                               
The icons can either be PNG (.png) or SVG (.svg) files. There are some problems with librsvg's usage of some svg files it seems. Most simple SVG files _cannot_ be loaded by librsvg. More investigation is needed to see what kind of SVG's work. See note in section 6.
.SH "DEPENDENCIES"
.TP 
gdk\-pixbuf\-2
.TP 
pkg\-config     \- GNU autoconf and automake already have it I believe
.TP 
librsvg\-2.0.1  \- nautilus has this already I believe
.TP 
other gnome stuff \- if you have everything for librsvg then you should be good.
                                                                                                           
.SH "INSTALLING"
Decompress and untar the tar.gz file into a directory. In that directory:
.IP                                
$> make
.br 
$> su
.br 
$> make install
.LP 
Make install will copy the executable\-binary file to /usr/local/bin/idesk.
.SH "CONFIGURING"
\fBSTEPS\fR
.PP 
\fB1.\fR Following the syntax described in \fIideskrc(5)\fR, create a file
in your home directory named .ideskrc.
.PP 
\fB2.\fR Create a directory called .idesktop/ in your home directory. 
.PP 
\fB3.\fR Inside the new directory, create an icon file with the extension 'lnk'(e.g., home.lnk) as deescribed in \fILINKS FILES\fR section belw.
.PP 
\fB4.\fR Start idesk as described in \fIRUNNING\fR below, or kill and
restart idesk if it's already running.
.PP 
\fB5.\fR Move your new icon to where you would like it to be, and verify
it works correctly.
.PP 
\fB6.\fR Repeat steps 3\-5 for any additional icons you would like to have.
.PP 
\fB7.\fR After you have your icons finished and where you want them, change
\fILocked\fR from 'false' to 'true' in .ideskrc.
.PP 
\fB8.\fR (optional) Add 'idesk' to your .xinitrc or other startup scripts to run it automatically.

.SH "LINK FILES"
In general link file will look like this:
.IP 
table Icon
  Caption: Home
  Command: nautilus /home/you
  Icon: /home/you/.idesktop/home.png
.br 
end
.LP                              
These are the options for icon file, they should mostly be self\-explantory. The Icon option is the graphic file for the icon image (either a png file or a svg file). The Execute[i] action (in .ideskrc) runs the Command[i]. If the Caption field is blank or just one space, then no caption will be created for the icon.

.IP                             
table Icon
  Caption: Tux
  Icon: /home/you/icons/tux2.svg
  Width: 600
  Height: 700
  X: 680
  Y: 174
  Command[0]: echo 'Linux rocks!'
.br 
end
.LP                                                                                                                
\fBImportant for SVG\fR
.br 
If you use a svg icon need to set Width and Height to your desired pixel size. Just make sure that the X value plus the width doesn't exceed your window diemensions, you get a segfault (same for Y value and height). It is best to set X and Y to zero to prevent this.
.SH "DEFAULT USAGE"
.TP 
Double click with the first mouse button will run the command.
.TP 
Click and drag with the first mouse button moves the icon (if not locked).
.TP 
Double\-click with the middle mouse button reloads the icons and regenerates background. Useful after changing wallpapers to clear graphical artifacts.
.TP 
Double\-click with the right mouse button to toggle the lock state. The state will be saved in the config file, so it will be remembered next startup.
.SH "RUNNING"
Idesk runs as a background process.  One suggested way to start idesk is:
.IP 
nohup idesk > /dev/null &
.PP 
After Idesk is running, click on an icon to start whatever command you 
assigned it.  Currently 'kill \-HUP' will terminate the program.  It is 
required to restart idesk when you add new icons (.lnk files), unless
you are running some other utility that runs on top of idesk, such as
Fluxspace.

You can reload existing .lnk files in ~/.idesktop/ by double middle\-clicking 
on any icon.

.SH "SEE ALSO"
\fIideskrc(5)\fR

.SH "BUGS"
High\-Contrast currently not implemented. 
.br 
segfault if SVG image extends beyond window in config file
.SH "PROGRAM AUTHORS"
.IP 
Chris Roberts (nikon) <nikon@sc.rr.com>
.br 
Bryn (curious) <curious@ihug.com.au>
.br 
Christopher Morris <cmorri9@lsu.edu>
.br 
Tim Finley <timmfin@timmfin.net>
.SH "MANPAGE AUTHOR"
.IP 
Dylan Carlson <absinthe@gentoo.org>
.br 
Sergey Kuleshov <svyatogor@gentoo.org>
