.TH "ideskrc" "5" "" "" ""
.SH "NAME"
ideskrc \- Configuration file for idesk(5)
.SH "USAGE"
The .ideskrc file needs to be placed in the root of your home directory.
.SH "FORMAT"
The structure of the file is as follows:
.IP
table Config
  <setting>: <value>
.br
end
.PP
Anything else in the file will be ignored.
.SH "SETTINGS"
\fIBold\fR: boolean (true/false)  If 'true', this will make your font bold.

\fIDoubleClick\fR: boolean (true/false)  If 'false', you only need to click
once to launch the icon.  If 'true' (default) icons require double-clicking.
Note: This feature may not be available in your platform's version of idesk.

\fIFontColor\fR: (hex value, #RRGGBB)  Sets the color of the desired font.

\fIFontName\fR: the name of the desired font.

\fIFontSize\fR: the point size of the desired font.

\fIHighContrast\fR: boolean (true/false)  An alternative to Shadow.  If 'true',
draws a border around the text in the opposite color.  If 'false', it is
disabled.

\fILocked\fR: boolean (true/false).  Prevents the icons from being moved.

\fIPaddingX\fR, \fIPaddingY\fR: (pixels)  The amount of desired padding around the icon.

\fIShadow\fR:  boolean (true/false)  Turning this on will draw a drop 
shadow of color ShadowColor behind the text.  The shadow will be ShadowX 
pixels right and ShadowY pixels down (negative values will work).  Both 
ShadowX and ShadowY default to 1.

\fIShadowColor\fR:  (hex value, #RRGGBB)  Sets the color of the drop shadow.

\fIShadowX\fR, \fIShadowY\fR: (pixels) Sets the size and direction of the drop shadow.

\fITransparency\fR: (0-255)  Determines the alpha transparency of the icon 
before a mouse-over.  If '0', the icon will be invisible without moving your 
mouse over it.    If '255', mouse-over glow is disabled.
.SH "EXAMPLE"
table Config
  FontName: verdana
  FontSize: 11
  FontColor: #ffffff
  PaddingX: 25
  PaddingY: 25
  DoubleClick: false
  Transparency: 100
  HighContrast: false
  Locked: false
  Shadow: true
  ShadowColor: #000000
  ShadowX: 222
  ShadowY: 22
  Bold: false
.br
end
.SH "SEE ALSO"
\fIidesk(1)\fR

.SH "PROGRAM AUTHORS"
.IP
Chris Roberts (nikon) <nikon@sc.rr.com>
.br
Bryn (curious) <curious@ihug.com.au>
.br
Christopher Morris <cmorri9@lsu.edu>
.br
Tim Finley <timmfin@timmfin.net>
.SH "MANPAGE AUTHOR"
.IP
Dylan Carlson <absinthe@gentoo.org>
