#!/bin/sh

if [ ! -d ~/.epsxe ]; then
	echo You are running ePSXe for the first time.
	echo Setting up your ePSXe environment... Please wait...
	
	mkdir -p $HOME/.epsxe
	cd $HOME/.epsxe
	mkdir memcards bios cfg cheats snap sstates patches plugins
	cp /etc/epsxe/keycodes.lst keycodes.lst

	ln -s /usr/lib/psemu/plugins/* plugins/
	ln -s /opt/epsxe/epsxe epsxe

	cd bios
	if [ -f /usr/lib/psemu/bios/scph1001.bin ]; then
		ln -s /usr/lib/psemu/bios/scph1001.bin .
	else
		echo -e "\007"
		echo "*** Put your BIOS file into $HOME/.epsxe/bios,"
		echo "    or ePSXe may not work!"
		echo ""
		echo " Hit enter key to continue..."
		read
	fi
fi

cd $HOME/.epsxe

ln -s /usr/lib/psemu/plugins/* plugins/
ln -s /usr/lib/psemu/cfg/* cfg/
ln -s /usr/lib/psemu/cheats/* cheats/

./epsxe
