# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

MODULE_AUTHOR="SHEVEK"

inherit perl-module

DESCRIPTION="Asynchronous DNS helper for high volume applications"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~amd64"

RDEPEND="dev-perl/Net-DNS"
DEPEND="${RDEPEND}"
SRC_TEST="do"
