# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="4"

MODULE_AUTHOR="MKUTTER"

inherit perl-module

SRC_TEST="do"

DESCRIPTION="SOAP with WSDL support"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE="test"

RDEPEND="dev-perl/TimeDate
	dev-perl/TermReadKey
	dev-perl/XML-Parser
	dev-perl/URI
	>=dev-perl/Class-Std-Fast-0.0.8
	dev-perl/Template-Toolkit"

DEPEND="${RDEPEND}
	test? (
		virtual/perl-Test-Simple
		virtual/perl-Getopt-Long
		virtual/perl-Storable
	)
	virtual/perl-Module-Build"
