# Copyright 1999-2001 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later

inherit kde-base || die

need-kde 3
# despite being a kde3 app, its configure script was generated by autoconf 2.13 so:
need-autoconf 2.1
DESCRIPTION="KDE MSN Messenger"
SRC_URI="mirror://sourceforge/kmerlin/${P}.tar.gz"
HOMEPAGE="http://kmerlin.olsd.de"


