# Copyright 1999-2001 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/net-im/kmerlin/kmerlin-1.0-r1.ebuild,v 1.3 2002/07/17 09:08:08 seemant Exp $

inherit kde-base || die

need-kde 3
# despite being a kde3 app, its configure script was generated by autoconf 2.13 so:
need-autoconf 2.1

DESCRIPTION="KDE MSN Messenger"
SRC_URI="mirror://sourceforge/kmerlin/${P}.tar.gz"
HOMEPAGE="http://kmerlin.olsd.de"

SLOT="0"
LICENSE="GPL-2"
KEYWORDS="x86"
