#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	need net
}

start() {
	ebegin "Starting flowscan processing"
	cd /var/lib/flows ; start-stop-daemon --start --quiet -c flows:flows --exec bin/flowscan \
	-p /var/run/flows/flowscan.pid -m -b >> /var/log/flowscan 2>&1 </dev/null & >/dev/null
}

stop() {
	start-stop-daemon --stop --quiet -p /var/run/flows/flowscan.pid
}
