# This is a make file inclusion, to be included in all the Netpbm make
# files.

# This file is meant to contain variable settings that customize the
# build for a particular target system configuration.

# The distribution contains the file Makefile.config.in and an exact
# copy of it named Makefile.config.  You edit Makefile.config to fit
# your system and leave Makefile.config.in alone.

# As distributed, Makefile.config is complete and is what the
# maintainer uses to build on his GNU/Linux/x86 system.

# Some of the variables that the including make file must set for this
# file to work:
#
#  SRCDIR: The directory at the top of the Netpbm source tree.  Note that
#  this is typically a relative directory, and it must be relative to the
#  make file that includes this file.  So it's normally "..".
#
#  CDEBUG: temporary extra compiler options for every compile.  Normally, 
#  you set this this via the Make command line, e.g. "make CDEBUG=-g" or
#  "make CDEBUG=-Werror".

# STATICLIB = Y means to build the Netpbm and Tiff libraries (if
# built) as static libraries instead of shared.  With static
# libraries, you should consider doing a merge build ('make merge')
# instead of the default to save disk space and memory.
#
# For cygwin, only static libraries work, so set STATICLIB = Y  .

STATICLIB = N

# The following are commands for the build process to use.  These values
# do not get built into anything.

# The C compiler (including macro preprocessor)
CC = gcc

# The linker.
LD = $(CC)

# MAKE is set automatically by Make to what was used to invoke Make.

INSTALL = install

# If you don't want to strip the binaries, just leave it null:
#STRIPFLAG =

# Normally the man pages are installed using "install".  But via this
# variable, you can use something else, for example a script that
# calls compress or pack.  Mantocat, included with Netpbm, is used on
# systems which use man pages in the "cat" format.

MANCP =	$(INSTALL) -m $(INSTALL_PERM_MAN)

AR = ar
RANLIB = ranlib

# C compiler options

# gcc:
# -ansi and -Werror should work too, but are not included
# by default because there's no point in daring the build to fail.
# -pedantic isn't a problem because it causes at worst a warning.
CFLAGS = -pedantic $(CFLAGS) -Wall -Wno-uninitialized $(CDEBUG)

# EXE is a suffix that the linker puts on any executable it generates.
# In cygwin, this is .exe and most programs deal with its existence without
# us having to know about it.  Some don't though, so set this:

EXE =
  
# linker options.  

LDFLAGS = -lz
#LDFLAGS = -Wl,--rpath,$(INSTALLLIBS)

# Linker options for created Netpbm shared libraries.

# Here, $(SONAME) resolves to the soname for the shared library being created.
# The following are gcc options.  This works on GNU libc systems.
LDSHLIB = -shared -Wl,-soname,$(SONAME)
CFLAGS_SHLIB = 

# The netpbm package contains a version of the Tiff library,
# libtiff.  If you want to use your own, fill in the appropriate paths
# below for the library and its interface headers

# Put the location of the TIFF library here.  Netpbm comes with a version
# of the TIFF library, so you can just specify the library in the Netpbm
# source tree unless you want to use your own TIFF library.  If you 
# specify the included TIFF library, 'make install' will also install it,
# but otherwise will not.

# Use the Tiff library included with Netpbm:
TIFFHDR_DIR = /usr/include 
TIFFLIB_DIR = /usr/lib

# If your Tiff library depends on libraries other than libc and libm,
# put the required linker options here.
TIFFLIB_LDFLAGS = -lz -ljpeg

# Put the location of your JPEG library here.
# If you want to build the jpeg converters or tiff
# converters that use jpeg compression in tiff files, you must have
# the jpeg library already installed.  Put the locations of the link
# library and the interface header files here.  If you do not have the
# JPEG library, and still want to successully build everything else,
# including non-JPEG versions of the tiff converters, put NONE for
# these.

# Special note for people using an already-installed Tiff library:  If
# your library was built with the JPEG stuff statically linked in, you
# don't need the JPEG library and the tiff converters will still do jpeg.
# If your library references a dynamic JPEG library, you must specify
# at least JPEGLIB_DIR here, or the tiff converters will not build at
# all.

JPEGLIB_DIR = /usr/lib/jpeg
JPEGHDR_DIR = /usr/include/jpeg

# PNG converters you must have the PNG library already installed.  Put
# the locations of the link library and the interface header files
# here.  If you do not have the PNG library, and still want to
# successully build everything else, put NONE for these.

PNGLIB_DIR = /usr/lib
PNGHDR_DIR = /usr/include/png

# And the Utah Raster Toolkit (aka URT aka RLE) library:

URTHDR_DIR = $(SRCDIR)/urt
URTLIB_DIR = $(SRCDIR)/urt

# These are -l options to link in the network libraries.  Often, these are
# built into the standard C library, so this can be null.  If you don't 
# want any network functions, make it NONE.  The only thing that requires
# network functions is the option in ppmtompeg to run it on multiple
# computers simultaneously.

NETWORKLD = -lnsl

VMS = 
#VMS:
#VMS = yes

# The following variables are used only by 'make install' (and the
# variants of it).  Paths here don't, for example, get built into any
# programs.

# EXCEPTION: If you used a -R $(INSTALL_LIBS) option above,
# then INSTALL_LIBS gets built into your shared libraries.

# File permissions for installed files.
# Note that on some systems (e.g. Solaris), 'install' can't use the 
# mnemonic permissions - you have to use octal.

# binaries (pbmmake, etc)
INSTALL_PERM_BIN =  755       # u=rwx,go=rx
# shared libraries (libpbm.so, etc)
INSTALL_PERM_LIBD = 755       # u=rwx,go=rx
# static libraries (libpbm.a, etc)
INSTALL_PERM_LIBS = 644       # u=rw,go=r
# header files (pbm.h, etc)
INSTALL_PERM_HDR =  644       # u=rw,go=r
# man pages (pbmmake.1, etc)
INSTALL_PERM_MAN =  644       # u=rw,go=r
# data files (pnmtopalm color maps, etc)
INSTALL_PERM_DATA = 644       # u=rw,go=r

# Everything gets installed relative to directory INSTALL_PREFIX.  If
# you're spreading Netpbm across your system, use "/".

INSTALL_PREFIX = /usr

# Some people specify PREFIX= on the command line, because that's conventional
ifneq ($(PREFIX)x,x)
  INSTALL_PREFIX = $(PREFIX)
endif

# Specify the directory where you want the executables.
# If you need scripts and binaries to be in different directories, you
# can set that up too.

INSTALLBINARIES = $(INSTALL_PREFIX)/bin
INSTALLSCRIPTS = $(INSTALL_PREFIX)/bin

# Specify the directory where you want the shared libraries
# installed.  For this to be effective, you must have set up this location
# to be searched by your system's program executor for runtime libraries.

INSTALLLIBS = $(INSTALL_PREFIX)/lib

# Specify the directories that you want the man page sources,
# plus the suffix you want them to have.

INSTALLMANUALS1 =	$(INSTALL_PREFIX)/share/man/man1
SUFFIXMANUALS1 =	1
INSTALLMANUALS3 =	$(INSTALL_PREFIX)/share/man/man3
SUFFIXMANUALS3 =	3
INSTALLMANUALS5 =	$(INSTALL_PREFIX)/share/man/man5
SUFFIXMANUALS5 =	5

# Specify the directory where you want the interface header files for
# the Netpbm (and possibly Tiff) libraries installed.

INSTALLHDRS = $(INSTALL_PREFIX)/include

# Specify the directory where you want data files that the Neptbm programs
# access to be installed

INSTALLDATA = $(INSTALL_PREFIX)/lib


#NETPBMLIBSUFFIX is the suffix on the filename of the generated and installed
#Netpbm libraries.  But you can't make it just anything, because there has to
#be a rule in the makefiles to make whatever the fliename turns out to be.
#Only .a and .so work.
ifeq ($(STATICLIB),Y)
  NETPBMLIBSUFFIX = a
  LIBTIFFSUFFIX = a
else
  NETPBMLIBSUFFIX = so
  LIBTIFFSUFFIX = so
endif





