#!/bin/sh
# Copyright (c) 2003 TransGaming Technologies Inc.
# Startup script for Point2Play.
# Version 1.1 Nov.26, 2003 

if !([ -e "$HOME/.point2play" ]); then
	mkdir "$HOME/.point2play"
fi

export P2PPATH=/usr/lib/transgaming_point2play
python ${P2PPATH}/Point2Play_gui.py "$@"
