#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later

# NB: Config is in /etc/conf.d/spamd.conf

depend() {
	need net
	before mta
}

pidfile=/var/run/spamd.pid

start() {
	ebegin "Starting spamd"
	start-stop-daemon --start --quiet \
		--exec /usr/bin/spamd -- -d -r ${pidfile} \
			${SPAMD_OPTS}
	eend $? "Failed to start spamd"
}

stop() {
	ebegin "Stopping spamd"
	start-stop-daemon --stop --quiet --pidfile ${pidfile}
	eend $? "Failed to stop spamd"
}

# vim:ts=4 noexpandtab ft=sh:
