.TH pkglist "1" "May 2001" "portage 1.5" 
.SH NAME
pkglist \- manual page for the pkglist program, a program to print out a list of installed packages.
.SH SYNOPSIS
.B pkglist
.SH DESCRIPTION
The pkglist command is a command-line program that searches the /var/db/pkg tree
for .ebuild files and makes a list of what it finds.  (Any ebuilds in
/var/db/pkg are necessarily installed packages).
.PP
.SH OPTIONS 
\fInone\fR
.TP
This program is too simple; it has no options.
.TP
.SH AUTHOR
Grant Goodyear <grant@gentoo.org>
.SH "SEE ALSO"
ebuild(1) emerge(5)
