#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/metasploit/files/msfweb3.3.initd,v 1.1 2010/03/01 12:52:51 patrick Exp $

PIDFILE=/var/run/msfweb3.3.pid

start() {
	ebegin "Starting msfweb3.3"
	start-stop-daemon --start --quiet --background --startas msfweb3.3 --exec /usr/lib/metasploit3.3/msfweb \
		--pidfile ${PIDFILE} --make-pidfile -- ${MSF_OPTS}
	eend $?
	einfo "Note: msfweb3.3 is started but needs some before it serves clients."
}

stop() {
	ebegin "Stopping msfweb"
	start-stop-daemon --stop --quiet -s 9 --pidfile ${PIDFILE}
	eend $?
}
