#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/metasploit/files/msfweb3.2.initd,v 1.1 2009/07/08 09:09:41 pva Exp $

PIDFILE=/var/run/msfweb3.2.pid

start() {
	ebegin "Starting msfweb3.2"
	start-stop-daemon --start --quiet --background --startas msfweb3.2 --exec /usr/lib/metasploit3.2/msfweb \
		--pidfile ${PIDFILE} --make-pidfile -- ${MSF_OPTS}
	eend $?
	einfo "Note: msfweb3.2 is started but needs some before it serves clients."
}

stop() {
	ebegin "Stopping msfweb"
	start-stop-daemon --stop --quiet -s 9 --pidfile ${PIDFILE}
	eend $?
}
