#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/metasploit/files/msfweb3.5.initd,v 1.1 2010/11/14 22:55:42 patrick Exp $

PIDFILE=/var/run/msfweb3.5.pid

start() {
	ebegin "Starting msfweb3.5"
	start-stop-daemon --start --quiet --background --startas msfweb3.4 --exec /usr/lib/metasploit3.4/msfweb \
		--pidfile ${PIDFILE} --make-pidfile -- ${MSF_OPTS}
	eend $?
	einfo "Note: msfweb3.5 is started but needs some before it serves clients."
}

stop() {
	ebegin "Stopping msfweb"
	start-stop-daemon --stop --quiet -s 9 --pidfile ${PIDFILE}
	eend $?
}
