# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/app-sci/kconvert/kconvert-1.1.ebuild,v 1.1 2003/02/17 20:34:37 mholzer Exp $

# This ebuild was generated by Ebuilder v0.4.

S="${WORKDIR}/${PN}"
DESCRIPTION="Converting Toolbetween Metric and Imperial"
SRC_URI="http://ftp.kde.com/Math_Science/KConvert/${P}.tar.gz"
HOMEPAGE="http://apps.kde.com/na/2/counter/vid/5632/kcurl"
LICENSE="GPL-2"
DEPEND=""
RDEPEND="virtual/glibc"
KEYWORDS="x86"
SLOT="0"

src_compile() {
	econf || die
	emake || die
}

src_install () {
	make DESTDIR=${D} install || die
	dodoc AUTHORS ChangeLog COPYING INSTALL README TODO
}

