.TH java-config "1" "March 2002" "java-config 0.2.0"
.SH NAME
java-config \- manual page for java-config, the Java configuration tool for
Gentoo
.SH SYNOPSIS
.B java-config
\fI[options]\fB

.SH DESCRIPTION
.PP
.I java-config
is used to query/set properties of your system's Java environment. It can be
used to list available VMs, java packages, set system default JVM and set user
default JVM.
.PP
In addition, it is used by Portage as a common interface to querying 
properties about the various JVMs.
.SH OPTIONS 
.TP
\fB--javac\fI
show full path to currently selected Java compiler.
.TP
\fB--jar\fI
show full path to currently selected
.I jar 
command
.TP
\fB--jdk-home\fI
show path to currently selected JDK
.TP
\fB--jre-home\fI
show path to currently selected JRE
.TP
\fB--java-version\fI
query current JVM for version
.TP
\fB--classpath[=package1,package2,...]\fI
calculate classpath for a package.
.TP
\fB--full-classpath[=package1,package2,...]\fI
calculate classpath with absolute paths ready to be assigned to CLASSPATH.
.TP
\fB--exec=filename\fI
figure full path to one of the JDK/JRE utilities, such as 
.I keytool
.
.TP
\fB--list-available-packages\fI
list available Java packages. Used for selection by
.I --classpath
and
.I --full-classpath
.
.TP
\fB--list-available-vms\fI
lists available JVMs. Used with 
.I --set-system-vm
and 
.I --set-user-vm
.
.TP
\fB--set-system-vm=<vm-id>\fI
sets the system-wide default JVM.
.TP
\fB--set-user-vm=<vm-id>\fI
sets the user-specific JVM by putting all necessary env vars into 
.I $HOME/.gentoo/java-env
.TP
\fB--set-system-classpath=package1,package2,...\fI
sets the system-wide default CLASSPATH.
.TP
\fB--set-user-classpath=package1,package2,...\fI
sets the user-specific CLASSPATH by putting all necessary env vars into 
.I $HOME/.gentoo/java-env-classpath
(sourced from $HOME/.gentoo/java-env).
.

.SH AUTHORS
Karl Trygve Kalleberg <karltk@gentoo.org>

.SH BUGS
It cannot be used to set default browser plugin yet.

.SH "SEE ALSO"
env-update(5)
.TP
The \fI/usr/bin/java-config\fR script. 
.TP
