#!/sbin/runscript

depend() {
	need net
	use jabber-server
}

start() {
	ebegin "Starting MSN Jabber Transport"
	jabberd -B -c /etc/jabber/msnt.xml -H /var/spool/jabber >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Stopping MSN Jabber Transport"
	kill `cat /var/log/jabber/msnt.pid`
	sleep 2
	if [ -f /var/log/jabber/msnt.pid ]; then
		kill -9 `cat /var/log/jabber/msnt.pid`
		rm -f /var/log/jabber/msnt.pid
	fi
	eend $?
}
