#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

opts="start stop status"

depend() {
        need net
}

start() {
        ebegin "Starting Camsource"
        start-stop-daemon --start --exec /usr/bin/camsource >/dev/null 2>&1
        eend $?
}

stop() {
        ebegin "Stopping Camsource"
        start-stop-daemon --stop --name camsource
        eend $?
}

