#!/sbin/runscript
# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/net-misc/knock/files/knockd.initd,v 1.1 2004/04/15 23:00:45 pyrania Exp $

depend() {
	need net
}

start() {
	ebegin "Starting knockd"
	start-stop-daemon --start --quiet --exec /usr/sbin/knockd -- ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping knockd"
	start-stop-daemon --stop --quiet --exec /usr/sbin/knockd
	eend $?
}
