# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/alsa-core/alsa-core-0.5.ebuild,v 1.1 2011/09/18 17:59:02 slyfox Exp $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Haskell binding to the ALSA Library API (Exceptions)."
HOMEPAGE="http://www.haskell.org/haskellwiki/ALSA"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.10.4
		media-libs/alsa-lib"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
