# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-dialup/isdndump/isdndump-0.01.ebuild,v 1.2 2005/10/04 18:45:49 mrness Exp $

inherit eutils rpm

DESCRIPTION="isdndump is the analyzer of ISDN D-channel messages generated by isdnlog."
HOMEPAGE="http://sourceforge.net/projects/isdndump/"
SRC_URI="mirror://sourceforge/isdndump/${P}-1.src.rpm"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE=""

DEPEND="sys-libs/ncurses"

RDEPEND="${DEPEND}
	net-dialup/isdn4k-utils"

src_compile() {
	emake CCDEBUGOPTS="${CFLAGS}" || die "emake failed"
}

src_install() {
	dobin isdndump
	dodoc ChangeLog README TODO
}
