# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15_rc2

inherit perl-module

DESCRIPTION="Interface to voice modems using vgetty"
HOMEPAGE="http://search.cpan.org/~yenya/"
SRC_URI="mirror://cpan/authors/id/Y/YE/YENYA/${P}.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"

SRC_TEST="do"
