#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-misc/zebra/files/zebra.initd,v 1.3 2004/07/15 00:16:56 agriffis Exp $

depend() {
	need net
}

start() {
	ebegin "Starting zebra"
	start-stop-daemon --start --quiet  --exec /usr/sbin/zebra -- ${OPTS}
	eend $?
}

stop() {
	ebegin "Stopping zebra"
	start-stop-daemon --stop --quiet  --exec /usr/sbin/zebra
	eend $?
}
