#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-emulation/qemu-guest-agent/files/qemu-ga.init,v 1.1 2012/07/28 22:00:05 cardoe Exp $

depend() {

}

start() {
    GA_METHOD=${GA_METHOD:-virtio-serial}
    GA_PATH=${GA_PATH:-/dev/virtio-ports/org.qemu.guest_agent.0}

    ebegin "Starting QEMU Guest Agent"

    start-stop-daemon --start --pidfile /var/run/qemu-ga.pid \
        --exec /usr/bin/qemu-ga -- -m ${GA_METHOD} -p ${GA_PATH} \
        -l /var/log/qemu-ga.log -d

    eend $?
}

stop() {
    ebegin "Stopping QEMU Guest Agent"

    start-stop-daemon --stop --pidfile /var/run/qemu-ga.pid

    eend $?
}
