#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-firewall/guarddog/files/guarddog.init,v 1.1 2009/04/29 02:29:42 darkside Exp $

depend() {
	after iptables
	before ddclient
}

start() {
	ebegin "Applying firewall rules - Guarddog"
	/etc/rc.firewall
	eend $? "Firewall rules not set"
}
