#!/sbin/runscript

instance=`basename ${1}`
instance="${instance/*\./}"

depend() {
	use net
}

start()	{
	ebegin "Starting aolserver - $instance"
	env LD_LIBRARY_PATH=/usr/lib/aolserver/lib \
	start-stop-daemon --start --quiet --exec /usr/bin/nsd -- \
	    -t /etc/aolserver/$instance.tcl \
	    -u aolserver \
	    -g web
	eend $?
}

stop ()	{
	ebegin "Stopping aolserver - $instance"
	start-stop-daemon --stop --quiet --pidfile /var/run/aolserver/$instance.pid
	eend $?
}
