# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# Maintainer: David Holm <david@realityrift.com>
# $Header: /var/cvsroot/gentoo-x86/app-office/ooodi/ooodi-0.55.ebuild,v 1.2 2003/02/13 09:18:44 vapier Exp $

# This ebuild was generated by Ebuilder v0.4.

DESCRIPTION="OOodi provides an automated dictionary installer for the OpenOffice.org word processer. It uses GTK+ for the user interface and libcurl for automated download of selected dictionaries."
SRC_URI="http://switch.dl.sourceforge.net/sourceforge/ooodi/OOodi-0.55.tar.gz"
HOMEPAGE="http://ooodi.sourceforge.net/"
LICENSE="GPL-2"

SLOT="0"
KEYWORDS="x86"
IUSE=""
DEPEND="net-ftp/curl
	x11-libs/gtk+"

P="OOodi-0.55"

src_compile() {
	./configure \
		--host=${CHOST} \
		--prefix=/usr \
		--infodir=/usr/share/info \
		--mandir=/usr/share/man || die "./configure failed"
	emake || die
}

src_install () {
	make DESTDIR=${D} install || die
	dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}


