# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

MODULE_AUTHOR="RICKM"
MODULE_A="${P}.tgz"

inherit perl-module

DESCRIPTION="Parse and Format DateTimes using Strptime"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"

DEPEND="dev-perl/DateTime
	dev-perl/DateTime-Locale
	dev-perl/DateTime-TimeZone
	>=dev-perl/Params-Validate-0.91
	dev-lang/perl"
