#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/buildbot/files/buildbot.initd,v 1.1 2006/09/25 17:42:37 marienz Exp $

depend() {
	need net
}

checkconfig() {
	if [[ -z "${BASEDIR}" ]]; then
		eerror "BASEDIR not set"
		return 1
	fi
	if [[ -z "${USERNAME}" ]]; then
		eerror "USERNAME not set"
		return 1
	fi
	if [[ ! -d "${BASEDIR}" ]]; then
		eerror "${BASEDIR} is not a directory"
		return 1
	fi
	if [[ ! -e "${BASEDIR}/buildbot.tac" ]]; then
		eerror "${BASEDIR} does not contain buildbot.tac"
		return 1
	fi
}

start() {
	checkconfig || return 1
	ebegin "Starting buildslave in ${BASEDIR}"
	# We set HOME here to make something valid show up in the env of child
	# processes spawned by the buildslave.
	start-stop-daemon --start -c "${USERNAME}" --quiet \
		--env HOME="${BASEDIR}" \
		--exec /usr/bin/twistd -- \
		--no_save \
		--logfile="${BASEDIR}/twistd.log" \
		--pidfile="${BASEDIR}/twistd.pid" \
		--python="${BASEDIR}/buildbot.tac"
	eend $?
}

stop() {
	ebegin "Stopping buildslave in ${BASEDIR}"
	start-stop-daemon --stop --quiet --pidfile "${BASEDIR}/twistd.pid"
	eend $?
}
