# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="4"

MODULE_AUTHOR="RJBS"

inherit perl-module

SRC_TEST="do"

DESCRIPTION="rewrite strings based on a set of known prefixes"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

RDEPEND=">=dev-perl/Sub-Exporter-0.982.0
	dev-lang/perl"
DEPEND="${RDEPEND}"
