#!/sbin/runscript
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-misc/rabbitmq-server/files/rabbitmq-server.init,v 1.2 2010/08/02 23:56:58 hollow Exp $

depend() {
	need net
	use dns
}

start() {
	export HOME=/var/empty
	ebegin "Starting RabbitMQ..."
	rabbitmq-server -detached
	eend $?
}

stop() {
	ebegin "Stopping RabbitMQ..."
	rabbitmqctl stop
	eend $?
}

