# Distributed under the terms of the GNU General Public License, v2 or later
# Author Frédéric Brin <duckx@libertysurf.fr>, Jonas Berlin <jonas@berlin.vg>

A="pccts133mr24.zip"
S=${WORKDIR}/pccts
DESCRIPTION="An embedded C++ parser generator"
SRC_URI="http://www.polhode.com/${A}"
HOMEPAGE="http://www.polhode.com/"

DEPEND="app-arch/unzip"

src_unpack() {
	unpack ${A}

	echo Patching support/genmk/genmk.c..
	cp ${S}/support/genmk/genmk.c ${T}/genmk.c
	sed 's,/usr/local/pccts,/usr/lib/pccts,' ${T}/genmk.c > ${S}/support/genmk/genmk.c
}

src_compile() {
	try make MAKE=\""make ${MAKEOPTS}"\" COPT=\""${CFLAGS}"\"
}

src_install() {

	# The reason why stuff goes to /usr/lib is that there are
	# platform-dependent binaries being installed.

	# The reason why I put everything else (source code templates
	# etc) into /usr/lib too is to avoid breaking makefiles
	# generated by the "genmk" tool (which is included and already
	# patched a bit).

	# main binaries
	exeinto /usr/lib/pccts/bin
	doexe bin/{antlr,dlg,genmk,sor}

	# main includes
	insinto /usr/lib/pccts/include
	doins h/*

	# sorcerer includes
	insinto /usr/lib/pccts/sorcerer/include
	doins sorcerer/h/*

	# sorcerer libraries
	insinto /usr/lib/pccts/sorcerer/lib
	doins sorcerer/lib/*

	# documentation
	dodoc CHANGES* KNOWN_PROBLEMS* MPW_Read_Me README RIGHTS history.txt
	newdoc sorcerer/UPDATES sorcerer-UPDATES
	newdoc sorcerer/README sorcerer-README

	# manual pages
	doman dlg/dlg.1 antlr/antlr.1
}
