# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI=4

MODULE_AUTHOR="HACHI"
MODULE_VERSION=${PV:0:4}

inherit perl-module

DESCRIPTION="Network awareness and extensions for MogileFS::Server"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86 ~ppc"
IUSE=""

DEPEND="dev-perl/Net-Netmask
	dev-perl/Net-Patricia
	>=dev-perl/mogilefs-server-2.580.0"
