#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-dotnet/xsp/files/xsp.initd,v 1.1 2004/05/21 20:18:45 latexer Exp $

depend() {
	need net
	after dotnet
}

start() {
	ebegin "Starting xsp"

	start-stop-daemon --quiet --start \
		--background \
		--make-pidfile \
		--pidfile /var/run/aspnet/xsp.pid \
		--chuid aspnet \
		--exec /usr/bin/mono /usr/bin/xsp.exe -- --root ${MonoServerRoot} --port ${MonoServerPort} --nonstop
	eend $?
}

stop() {
	ebegin "Stopping xsp"
	start-stop-daemon -o --quiet --stop \
		--pidfile /var/run/aspnet/xsp.pid
	eend $?
}

