.\" Copyright (C), 2004  Free Software Foundation, Inc.
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation Licence.
.TH curphoo 1 2004-04-14 

.SH NAME
curphoo \- a curses-based Yahoo! Chat room client

.SH HOMEPAGE
.B http://savannah.nongnu.org/projects/curphoo/

.SH SYNOPSIS
.B curphoo
[option]...

.SH DESCRIPTION
curphoo provides a curses-based interface to Yahoo! Chat rooms.

.SH OPTIONS
.TP
.I "\-u username"
Sets the username to authenticate with to
.I username
.TP
.I "\-r room"
Sets the chat room to enter initially to
.I room
.TP
.I "\-l"
Keep a log of the chat session in ~/.curphoo/log
.TP
.I "\--norc"
Do not load configuration in ~/.curphoo/curphoorc
.TP
.I "\-h"
List command line help

.SH FILES
.TP
.I ~/.curphoo/buddies
List of usernames, one per line.  These users will be allowed to
private message you.
.TP
.I ~/.curphoo/color
Color configuration for the Curphoo user interface.
.TP
.I ~/.curphoo/exclude
List of usernames, one per line.  These users will be excluded from
automatic ignore operations.
.TP
.I ~/.curphoo/regex
List of regular expressions, one per line.  These expressions will
will be used to ignore matching lines.
.TP
.I ~/.curphoo/highlightuser
List of usernames, one per line.  These users will be highlighted
when they comment.
.TP
.I ~/.curphoo/highlightstr
List of strings, one per line.  Comments containing these strings
will be highlighted.
.TP
.I ~/.curphoo/ignore
List of usernames, one per line. These users will be ignored.

.SH "SEE ALSO"

.SH BUGS
All software contains bugs.  Should you find a bug, or have a request
for enhancement, please use the bug database at 
.NH
http://savannah.nongnu.org/bugs/?group=curphoo

.SH AUTHOR
Matthew Kennedy <mkennedy@gentoo.org>
