# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/kprof/kprof-1.4.2.ebuild,v 1.11 2004/12/31 16:08:49 weeve Exp $

inherit eutils kde

DESCRIPTION="A KDE3 visual tool helping developers to analyze the profiling results generated by code profilers."
HOMEPAGE="http://kprof.sourceforge.net/"
SRC_URI="mirror://sourceforge/kprof/${P}.tar.gz"

SLOT="0"
LICENSE="GPL-2"
KEYWORDS="x86 ~sparc"
IUSE=""

need-kde 3

src_unpack() {
	base_src_unpack
	# Rename the source directory to include the version to make the eclass happy
	mv ${WORKDIR}/${PN} ${WORKDIR}/${P}
	cd ${S}
	epatch ${FILESDIR}/include_cassert.patch
}
