# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/kprof/kprof-1.4.3.ebuild,v 1.5 2005/05/07 19:13:00 carlo Exp $

inherit kde eutils

S=${WORKDIR}/${PN}

DESCRIPTION="A KDE3 visual tool helping developers to analyze the profiling results generated by code profilers."
HOMEPAGE="http://kprof.sourceforge.net/"
SRC_URI="mirror://sourceforge/kprof/${P}.tar.bz2"

SLOT="0"
LICENSE="GPL-2"
KEYWORDS="x86 ~sparc ~ppc"
IUSE=""

need-kde 3

src_unpack(){
	kde_src_unpack
	epatch ${FILESDIR}/${P}-configure-arts.diff
}
