# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-util/kprof/kprof-1.4.3.ebuild,v 1.7 2006/06/25 19:33:54 blubb Exp $

inherit kde eutils

S=${WORKDIR}/${PN}

DESCRIPTION="A KDE3 visual tool helping developers to analyze the profiling results generated by code profilers."
HOMEPAGE="http://kprof.sourceforge.net/"
SRC_URI="mirror://sourceforge/kprof/${P}.tar.bz2"

SLOT="0"
LICENSE="GPL-2"
KEYWORDS="~amd64 ~ppc ~sparc x86"
IUSE=""

need-kde 3

PATCHES="${FILESDIR}/${P}-configure-arts.diff
	${FILESDIR}/${P}-gcc41.patch"

