#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-db/mongodb/files/mongodb.initd,v 1.3 2011/04/13 14:56:32 ultrabug Exp $

depend() {
	need net
}

start() {
	mkdir -p ${MONGODB_RUN:-/var/run/mongodb}
	chown ${MONGODB_USER:-mongodb}: ${MONGODB_RUN:-/var/run/mongodb}

	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --background --start --make-pidfile \
		--pidfile ${MONGODB_RUN:-/var/run/mongodb}/${SVCNAME}.pid \
		--chuid ${MONGODB_USER:-mongodb} \
		--exec ${MONGODB_EXEC:-/usr/bin/mongod} \
		-- \
		--bind_ip ${MONGODB_IP:-127.0.0.1} \
		--port ${MONGODB_PORT:-27017} \
		--dbpath ${MONGODB_DATA:-/var/lib/mongodb} \
		--unixSocketPrefix ${MONGODB_RUN:-/var/run/mongodb} \
		--logappend --logpath /var/log/mongodb/${SVCNAME}.log \
		${MONGODB_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --pidfile ${MONGODB_RUN:-/var/run/mongodb}/${SVCNAME}.pid
	eend $?
}
